### ISSUE TITLE
photo pasting error

### ISSUE THREAD

**Issue by cross-hello** [BoostIO/Boostnote#3562] opened 2020-04-29 05:41 UTC
# Current behavior

I don't know whether it is for the snipping tool I use, which Windows carry it natively. Boostnote sometime ***may lose the photo***.
# Expected behavior

# Steps to reproduce

1.  use snipping tool
2.  ctrl+v
3.  Then sometime photo lose.
![88a975d9](https://user-images.githubusercontent.com/42733664/80563923-0f16e780-8a1f-11ea-89f9-339dc326b4ec.JPG)

# Environment

- Boostnote version: 0.15.3
- OS version and name: Win7-64bits

**Comment by Flexo013** [comment] 2020-05-01 17:21
Duplicate of #3374

**Closed** 2020-07-11 14:26 UTC
