### ISSUE TITLE
Custom themes?

### ISSUE THREAD

**Issue by luxcem** [BoostIO/Boostnote#591] opened 2017-05-20 07:41 UTC
Is there a method to custom the themes available?

**Comment by kazup01** [comment] 2017-05-21 03:01
It can not do it at current version, but I have heard from many people that they want this feature.

**Comment by JSn1nj4** [comment] 2017-07-30 23:57
Would definitely love this too, even if just for the code editor / code blocks at first.

**Comment by asmsuechan** [comment] 2017-07-31 00:00
You can add your theme by the following method.
https://github.com/BoostIO/Boostnote/issues/200#issuecomment-271854423

**Comment by JSn1nj4** [comment] 2017-07-31 11:26
@asmsuechan what does that do exactly? Does it replace a built in theme?

**Comment by JSn1nj4** [comment] 2017-07-31 17:51
@asmsuechan sorry, I was responding from mobile before. I just found the folder in which this is located, and it seems like it would *partially* work.

The issue is that, on Windows, there's potential for any custom themes to get wiped out since the Windows app uses the Squirrel updater. So I'll try this out and keep my theme somewhere (possibly in boostnote 😉).

Also, after inspecting [this file][1], it would seem that adding a folder for custom themes shouldn't be _that_ difficult -- specifically after seeing [line 6][2] and [line 9][3].

Since `themes` is a constant, would it be possible to create a separate constant that would contain an array of custom themes located in a specified folder? 

[1]: https://github.com/BoostIO/Boostnote/blob/master/browser/lib/consts.js
[2]: https://github.com/BoostIO/Boostnote/blob/master/browser/lib/consts.js#L6
[3]: https://github.com/BoostIO/Boostnote/blob/master/browser/lib/consts.js#L9

**Comment by asmsuechan** [comment] 2017-07-31 23:50
I am willing to agree to your request.

**Comment by tatoosh** [comment] 2017-10-30 14:55
@JSn1nj4 how to change windows theme?

**Comment by Flexo013** [comment] 2019-07-27 00:38
I will close this issue for now as you can add your own custom css from the preferences.

@luxcem If you feel like something more has to happen with this issue, then feel free to reopen/recreate an issue.

**Closed by Flexo013** 2019-07-27 00:38 UTC
Labels: feature request :zap:, help wanted :sos:
