### ISSUE TITLE
Display snippet code inline instead of link

### ISSUE THREAD

**Issue by it4577** [BoostIO/Boostnote#3572] opened 2020-05-14 14:15 UTC
# Current behavior

Currently, when linking a snippet within a markdown note a link to the the snippet is created.

# Expected behavior

Desired result is to have an option/flag to display the code snippet inline (within the markdown note) and formatted appropriately based on language. This would reduce the size of markdown notes and allow for an additional usage of code snippets.

# Environment

- Boostnote version: 0.15.3
- OS version and name:  Windows 10

**Comment by Flexo013** [comment] 2020-05-18 18:15
Duplicate of #597

**Closed by Flexo013** 2020-05-18 18:15 UTC
Labels: feature request :star2:
