### ISSUE TITLE
[Bug] When using Prettify Markdown on a TODO list the progress bar disappears.

### ISSUE THREAD

**Issue by BramManuel** [BoostIO/Boostnote#3468] opened 2020-02-13 08:49 UTC
# Current behavior
After formatting a TODO list with Prettify Markdown that comes included in Boostnote.
The prettifyer causes the list to change in markdown, and the progress bar disappears.

Before: 
![Before](https://user-images.githubusercontent.com/27723033/74416288-39580080-4e45-11ea-9821-52e1b224874f.PNG)

After:
![After](https://user-images.githubusercontent.com/27723033/74416297-3e1cb480-4e45-11ea-8c43-94e0c379a75a.PNG)

# Expected behavior
After formatting the progress bar should stay and not disappear. 

# Steps to reproduce

1. Make a new note.
2. Make a list of TODO items
- [ ] Test 1
- [ ] Test 2
- [ ] Test 3
3. Format the note with the shortcut, in my case "Ctrl + Shift + F"

# Environment

- Version: Boostnote 0.14.0
- OS Version and name : Windows 10 Enterprise

**Comment by Flexo013** [comment] 2020-02-15 16:43
Duplicate of #3361

**Closed by Flexo013** 2020-02-15 16:43 UTC
