### ISSUE TITLE
Boostnote UI close, but process not close 

### ISSUE THREAD

**Issue by ushell** [BoostIO/Boostnote#1679] opened 2018-03-14 14:20 UTC
i install new version app in debian, when open app and close it, the process not close.

use `ps axu |grep Boostnote` show in process list.

why i click the close button, app not real close ?

**Comment by Rokt33r** [comment] 2018-03-15 04:02
I’ll check it.

**Comment by jkbecker** [comment] 2018-03-17 22:00
Yes! I have this as well on linux mint 18.3.

When you close the Boostnote window it goes away, but three process remain alive:

``` 
jkbecker 14518  0.2  0.4 1477804 66228 ?       Sl   14:27   0:33 /usr/share/boostnote/Boostnote
jkbecker 14521  0.0  0.0 333972  4056 ?        S    14:27   0:00 /usr/share/boostnote/Boostnote --type=zygote --no-sandbox
jkbecker 14552  0.2  0.9 1199664 158124 ?      Sl   14:27   0:35 /usr/share/boostnote/Boostnote --type=renderer --no-sandbox --primordial-pipe-token=[...] --lang=en-US --app-path=/usr/share/boostnote/resources/app --node-integration=true --webview-tag=true --no-sandbox --enable-blink-features=OverlayScrollbars --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=[...lots-of-numbers...] --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --disable-gpu-compositing --service-request-channel-token=[...] --renderer-client-id=3 --shared-files=v8_natives_data:100,v8_snapshot_data:101
``` 

When I try to launch Boostnote the next time, the window just flashes briefly and then goes away. I have to go and kill the old processes before I can launch the Boostnote application successfully again.

Are there some logs I can post which would help here?

**Comment by Rokt33r** [comment] 2018-03-22 12:40
@ushell @jkbecker Are you using Cinnamon? I couldn't reproduce this problem on my Linux(Ubuntu with Unity).
Anyway, I'm going to apply some potential fix to the next version.

**Comment by jkbecker** [comment] 2018-03-22 12:44
@Rokt33r yes, I'm using Cinnamon. Let me know if I can install the fix somewhere to test!

**Comment by Rokt33r** [comment] 2018-03-22 13:11
Haha I assume this will fix it. https://github.com/BoostIO/Boostnote/pull/1721
This PR has been merged. You can check this on master branch.

**Comment by marcinbojko** [comment] 2018-03-28 17:11
Sorry, Linux Mint+Cinnamon:
version 0.11.3


module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/share/boostnote/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/usr/share/boostnote/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/usr/share/boostnote/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by Rokt33r** [comment] 2018-04-03 19:34
It has been fixed by https://github.com/BoostIO/Boostnote/pull/1741. And, we're going to release new version in this weekend.

**Closed by Rokt33r** 2018-04-03 19:34 UTC
Labels: help wanted
