### ISSUE TITLE
About the preview mode ctrl +f search function

### ISSUE THREAD

**Issue by potester** [BoostIO/Boostnote#2735] opened 2018-12-20 12:28 UTC
First of all, I am very grateful to the developers for their efforts. I have a confusion. In the note preview mode, there is no search function, which leads to a half-day search. Can I add a preview mode search function?

**Comment by ZeroX-DG** [comment] 2018-12-20 14:17
Have you tried to search in the editor?

**Comment by potester** [comment] 2018-12-20 15:04
Search is available in the editor, but the visual experience is poor and the code block is not highlighted.

**Comment by ZeroX-DG** [comment] 2018-12-20 15:11
Looks like we gonna need some improvements on searching experience for each individual note. We have received some issues related to the poor searching experience. Unfortunately, I'm a bit busy now so maybe someone else can fix this but I'll also try to fix this issue when I have time.

**Comment by Flexo013** [comment] 2020-06-14 10:44
Duplicate of #2625

**Closed by Flexo013** 2020-06-14 10:44 UTC
Labels: feature request :star2:
