### ISSUE TITLE
Auto Scroll Problem in markdown editor with Images

### ISSUE THREAD

**Issue by saboorelahi** [BoostIO/Boostnote#3212] opened 2019-08-13 12:34 UTC
# Current behavior
Markdown Editor automatically scroll up and scroll down on editing something if image is included in the markdown file. I have made a video of the issue which can be opened by clicking the image below

[![Boostnote Issue related to scrolling](https://i.ibb.co/BcxL7yv/boostnote.png)](https://vimeo.com/353555936)

# Expected behavior
Markdown Editor should remain at its current position

# Steps to reproduce
1. Open Boostnote and make a markdown note
2. Add a lot of text and some image so that content can be scroll up or down. 

Sample Code can be found at the link below:

https://jsbin.com/xilepeceso/edit?html,output

# Environment

- Version : Boostnote 0.12.1
- OS Version and name : Linux Ubuntu 19.04

**Comment by Flexo013** [comment] 2019-08-13 14:01
Duplicate of #2886

**Closed by Flexo013** 2019-08-13 14:01 UTC

**Comment by saboorelahi** [comment] 2019-08-13 14:12
In issue #2886 it was described that the preview scroll up to the top. 
I am not sure whether it covered the case of editor going to the top automatically in case of images.
