### ISSUE TITLE
No Scroll Bar in Left Dir Navigate Window

### ISSUE THREAD

**Issue by StandOutstar** [BoostIO/Boostnote#3496] opened 2020-02-25 03:25 UTC
# Current behavior

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

## Desktop/Web
- Boost Note.next version: 0.15.0
- OS version and name: MacOS 10.15.3

## Mobile
- Boost Note app version: 
- OS version and name:

**Comment by Flexo013** [comment] 2020-02-25 21:57
Wrong repo (Boost Note.next vs Boostnote)

**Comment by Flexo013** [comment] 2020-02-25 21:57
Duplicate of #3490

**Closed by Flexo013** 2020-02-25 21:57 UTC
