### ISSUE TITLE
Boostnote always go back to the first page

### ISSUE THREAD

**Issue by gmqi** [BoostIO/Boostnote#3218] opened 2019-08-22 11:59 UTC
# Current behavior
If there have a picture link in the note (like the following), when I edit the note, Boostnote always go back to the first page. 
```
![Fig. 1](https://people.xiph.org/~jm/demo/rnnoise/noise_suppression.png)
```

# Expected behavior
When edit the note, Boostnote does not go back to the first page. 

# Steps to reproduce

1. Enter a picture link in a note.
    `![Fig. 1](https://people.xiph.org/~jm/demo/rnnoise/noise_suppression.png)`
2. Enter a character.
3. Boostnote go back the first page automaticly.

# Environment

- Version : 0.12.1
- OS Version and name : Win 7 / 10

**Comment by Flexo013** [comment] 2019-08-22 13:21
Duplicate of #2886

**Closed by Flexo013** 2019-08-22 13:21 UTC
