### ISSUE TITLE
`Copy Note Link` doesn't paste into Editor Correctly

### ISSUE THREAD

**Issue by RyanGreenup** [BoostIO/Boostnote#3427] opened 2020-01-11 00:38 UTC
# Current behavior

Using the Context Menu to 'Copy Note Link` and paste into the editor produces incorrect markdown syntax due to erroneous escape characters  (`\`)being inserted.

For example a link may be put in the clipboard like so

```
[📋 📘 Boostnote Markdown CheatSheet](:note:1aexxxa3-7xx0-4xx7-b45d-0xxxxxxxxd47)
```

but it will be pasted into the note like this:

```bash
\[📋 📘 Boostnote Markdown CheatSheet\](:note:1aexxxa3-7xx0-4xx7-b45d-0xxxxxxxxd47)

```

# Expected behavior

The clipboard should be pasted directly in so that the correct markdown syntax is used and the link can be followed.

# Steps to reproduce

1. Open a Note
2.  Right Click any note from the list and select `Copy Note Link`
3. Paste it into the editing pane

## Animation

![BoostNoteBug](https://user-images.githubusercontent.com/47832594/72195513-9148b500-340a-11ea-9181-4ad9b3258c5e.gif)

# Environment

- Version : Boostnote 0.14.0-0
- OS Version and name : Ubuntu 19.10

**Comment by Flexo013** [comment] 2020-01-12 21:40
On Windows 10 this behavior does not exist. The pasting is always like expected. 

@RyanGreenup Could you try pasting Ctrl+Shift+V versus the regular Ctrl+V? I think on of them tries to escape Markdown, and the other doesn't. That should fix the issue.

**Comment by RyanGreenup** [comment] 2020-01-12 21:45
Using Ctrl+Shift+V as opposed to Ctrl+V doesn’t change anything on my end, when I get time I’ll try using the `.appimage` Rather than the `.deb` to see if that helps.

**Comment by Flexo013** [comment] 2020-01-14 06:27
Duplicate of #2628

**Closed by Flexo013** 2020-01-14 06:27 UTC
Labels: needs more info :information_source:
