### ISSUE TITLE
Cannot click "Disable Direct Write" button

### ISSUE THREAD

**Issue by Aaron-Bird** [BoostIO/Boostnote#3494] opened 2020-02-25 09:51 UTC
# Current behavior
![1](https://user-images.githubusercontent.com/25508292/75234870-4e923f00-57f6-11ea-8939-e51211923753.gif)  

https://github.com/BoostIO/Boostnote/blob/d727a6110adde03d1b5bfad9e121603acb9e83a7/browser/main/modals/PreferencesModal/UiTab.js#L344

What's the use of this button?

# Environment

- Version : 0.15.0
- OS Version and name : Windows

**Comment by Flexo013** [comment] 2020-02-25 21:52
Duplicate of #3368

**Closed by Flexo013** 2020-02-25 21:52 UTC
