### ISSUE TITLE
Text '0.' disappears after pressing Enter

### ISSUE THREAD

**Issue by kpsychas** [BoostIO/Boostnote#3376] opened 2019-11-22 08:28 UTC
# Current behavior
Initial state: a line has characters "0." (without quotes) followed or preceded by any number 
of spaces and cursor is on that line.
After Enter is pressed: the characters before cursor and a character right after it are deleted
and new line is inserted at the cursor position.

# Expected behavior
After Enter is pressed: new line is inserted at the cursor position.

# Steps to reproduce

1. Create an empty note and write "0." (without quotes) on first line
2. Press Enter right after

# Environment

- Version : 0.13.0
- OS Version and name : Windows 10 Pro

**Comment by Flexo013** [comment] 2019-11-22 10:20
Confirmed on Ubuntu 16.04

**Comment by arcturus140** [comment] 2019-11-22 10:59
I think I can explain the bug:

reason for this is that boostnote automatically adds a new enumeration each time [[Enter]] is pressed: 

Example: 

    1. numerated
    2. list + [[Enter]]
    3. 

To exit enumeration the last enumeration is removed if it is empty. This causes to remove everything with the pattern:

    \d+\. *

followed by [[Enter]].

Version: all
OS Version and name: all

**Comment by Flexo013** [comment] 2019-11-22 11:28
@arcturus140 Yeah, you're right! The same behavior occurs with any numbered list. So '1.', '2.', and so on. They all perform this behavior as it is a consequence of being an empty list item.

This might just be a `won't fix` or `works as intended` issue then.

**Comment by Flexo013** [comment] 2019-11-22 11:30
I'm closing this for now, but feel free to keep this discussion going. We might decide to reopen it and change stuff.

**Closed by Flexo013** 2019-11-22 11:30 UTC
Labels: won’t fix :x:

**Comment by arcturus140** [comment] 2019-11-22 11:45
well, for Boostnote.next I believe a more robust solution would be to define scopes and apply then to the document. This allows to apply operations only on a specific scope, like list, TOC, code, code.js, etc. 

but this is an entire different issue, also not something I can easily make any suggestions on.
