### ISSUE TITLE
Missing system tray icon on Linux / start minimized

### ISSUE THREAD

**Issue by brpaz** [BoostIO/Boostnote#1116] opened 2017-11-12 18:55 UTC
Hello.
I just used Boostnote on Windows and notice the the application has a system tray icon, but not on Linux. Also finder does not work on Linux also. Any particular reason?

I would like to be able to start Boostnote on system boot, but minimized to tray.

**Comment by kohei-takata** [comment] 2017-11-13 14:45
Hi @brpaz !
Thanks for your opening an issue!

Could you put some screenshots here?
I want to see some screenshots about these two issue.
- Boostnote on Linux does not have a system tray icon.
- Finder does not work on Linux.

I do not have an idea to implement this feature, so I will study!
Also, PR is welcome!
- Boostnote is not able to start on system boot, but minimized to tray

**Comment by brpaz** [comment] 2017-11-18 18:56
Hmm, there is no really any useful screenshots I can take. Simple, when I open boostnote, no icon is displayed on System tray, unlike windows, for example, which displays an icon with options "toggle main" and "toggle finder" or something like that.

For finder, I simple cant open it (hotkey does nothing)

**Comment by whizark** [comment] 2017-11-20 11:48
For Finder, `lib/main-app.js` seems not to spawn finder window process on Linux.
After I add `spawnFinder()` to [Boostnote/main-app.js](https://github.com/BoostIO/Boostnote/blob/master/lib/main-app.js#L111), it works (at least on Ubuntu).

The feature has been removed by [Disable Finder and Auto-update on Linux · BoostIO/Boostnote@cfa251b](https://github.com/BoostIO/Boostnote/commit/cfa251b1580260e9e01139e706aa854dcc996675) on 7 Apr 2016, but I cannot find the reason.

![finder](https://user-images.githubusercontent.com/1211058/33016997-004b116c-ce34-11e7-90e9-4e351672ccc8.gif)

**Comment by Redsandro** [comment] 2018-02-09 20:15
This is a bug and a feature request in one issue. The bug is a duplicate of #377.

**Closed** 2018-05-07 06:52 UTC
Labels: bug
