### ISSUE TITLE
Features: Multiselect tagging and some other improvements

### ISSUE THREAD

**Issue by manavortex** [BoostIO/Boostnote#2632] opened 2018-11-21 09:27 UTC
Hello there, 
first of all, I'm on OsX, since that's going to matter. Here's what I'd love to see:

I've just imported all my notes from Evernote via ever2boost, and I now have a bunch of un-tagged folders. Rather than to re-tag all my notes manually, it would be great if I could bulk-tag notes (multi select). Is it possible yet, and if not, are you interested in hacking it in? 

Multiselect: When I click on a note in the list next to the folders and press cmd+A, the entire UI gets selected, rather than all notes in the folder. Could that be fixed? 

Editor view: I'd love to have an option to switch the editor based on folders. Also, a "markdown only"-view would be amazing. 

Hotkeys: I haven't found a hotkey that lets me focus the find window. I'd love to have two, actually, one that lets me search in my current folder selection and one that lets me search in all may notes. 

Search: Is it possible to perhaps put the current folder into the search box, tag-style, so I can clear it with a backspace? 

Thank you for making this, it's great.

**Comment by ZeroX-DG** [comment] 2018-11-21 16:56
The multi select is not supported at the moment and tagging multi selected notes feature has been requested here: https://github.com/BoostIO/Boostnote/issues/2609 and of course, it hasn't been implemented in the current version. Feel free to open a PR :smile: 
Hotkey for focusing on the search bar is: `ctrl + l`
If you want to search with tags, please use: the tag view on the left menu bar (the one the right): 
![image](https://user-images.githubusercontent.com/12984316/48856259-8850ea80-ede8-11e8-9a9d-d8ed6cc5193e.png)
Editor view for markdown only can be toggle using the toggle mode button (`ctrl + m` hotkey)
![peek 2018-11-21 23-53](https://user-images.githubusercontent.com/12984316/48856340-b9311f80-ede8-11e8-9c85-2f64d874a263.gif)

**Comment by Flexo013** [comment] 2020-02-16 18:09
Duplicate of #2609

**Closed by Flexo013** 2020-02-16 18:09 UTC
Labels: feature request :star2:
