### ISSUE TITLE
Bad looking icon in windows taskbar

### ISSUE THREAD

**Issue by SrdjanMilic** [BoostIO/Boostnote#1515] opened 2018-02-06 17:08 UTC
![boostnote_bad_icon](https://user-images.githubusercontent.com/28996115/35872946-96639928-0b68-11e8-9bca-f6fc679900ad.PNG)

**Comment by Redsandro** [comment] 2018-02-09 20:12
Probably duplicate of #1488

**Comment by Flexo013** [comment] 2019-07-28 19:49
Duplicate of #1046

**Closed by Flexo013** 2019-07-28 19:49 UTC
