### ISSUE TITLE
Can not download from the website

### ISSUE THREAD

**Issue by Tao-Zhou** [BoostIO/Boostnote#3307] opened 2019-10-23 09:28 UTC
# Current behavior

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by arcturus140** [comment] 2019-10-23 09:53
hi,

the latest version of Boostnote can be downloaded from the following URL: https://boostnote.io/

**Comment by Tao-Zhou** [comment] 2019-10-23 10:33
> hi,
> 
> the latest version of Boostnote can be downloaded from the following URL: https://boostnote.io/

I know, but when I click the button, ERR_CONNECTION_REFUSED appeared.

**Comment by Tao-Zhou** [comment] 2019-10-23 11:00
> hi,
> 
> the latest version of Boostnote can be downloaded from the following URL: https://boostnote.io/

ok, I downloaded it with VPN

**Comment by Flexo013** [comment] 2019-10-23 12:17
Duplicate of #3303

**Closed by Flexo013** 2019-10-23 12:17 UTC
Labels: duplicate :no_entry_sign:
