### ISSUE TITLE
Make file names (human-)readable

### ISSUE THREAD

**Issue by fanrongqitiancai** [BoostIO/Boostnote#2048] opened 2018-06-08 08:13 UTC
# Current behavior
when I  create a new note,the file is .cson file format.but I hope to create it  as .md format.
the file name is not readable like this:769240df-bee4-4d8f-9fc2-e708782ec107.cson.
I hope that the file name is like this: JavaScript code -2018-06-08 16:13:18.md

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by Rokt33r** [comment] 2018-06-08 09:54
It should be nice to have. But, we have to prepare another space to store some metadata. 
I am actually considering to implement this on the renewed app, not the current app because the risk of migrating data is quite high.

**Comment by cselti** [comment] 2018-12-07 17:41
It can be solved, if the metadata (that is stored in the cson file) will be stored inside the markdown file between HTML comment tags ( \ ), similar like the generated ToC used now. The result will be a "standard" github markdown file, that can be editable with different editor on different platforms - like smartphone, web based editor, etc.

**Comment by Flexo013** [comment] 2019-08-06 03:06
Changing the file type is already being discussed in #490

**Comment by Flexo013** [comment] 2019-08-07 15:39
Duplicate of #1447

**Closed by Flexo013** 2019-08-07 15:39 UTC
Labels: feature request :zap:
