### ISSUE TITLE
Four consecutive quotes makes the note unable to load

### ISSUE THREAD

**Issue by HarZe** [BoostIO/Boostnote#3429] opened 2020-01-13 11:15 UTC
# Current behavior

When four consecutive quotes are written anywhere in a note with multiple lines, the note is not loaded after reloading. The _cson_ file is created, that's why I think it has something to do with parsing / loading the file.

Generated file:
```
createdAt: "2020-01-13T11:15:05.545Z"
updatedAt: "2020-01-13T11:15:13.825Z"
type: "MARKDOWN_NOTE"
folder: "693ce1062ba0c1e15d73"
title: "test"
tags: []
content: '''
  # test
  
  \''''
  
'''
linesHighlighted: []
isStarred: false
isTrashed: false
```

# Steps to reproduce

1. Create a new note
2. Give it a title in the first line and type `''''` (four quotes) in any other line
3. Reload (Ctrl+R) or reopen Boostnote

# Environment

- Version : 0.14.0
- OS Version and name : Manjaro - Kernel: 5.4.6-2-MANJARO

**Comment by arcturus140** [comment] 2020-01-13 17:13
duplicate of #300

**Comment by Flexo013** [comment] 2020-01-14 06:28
Duplicate of #300

**Closed by Flexo013** 2020-01-14 06:28 UTC
