### ISSUE TITLE
App fails to start more than once

### ISSUE THREAD

**Issue by davidsneighbour** [BoostIO/Boostnote#1459] opened 2018-01-25 08:10 UTC
I installed boostnote_0.8.20_amd64.deb on Ubuntu 17.10. The first start works fine. Closing the program down. The next start fails with the error message `Uncaught Exception: Error: Object has been destroyed at Function.<anonymous> (/usr/share/boostnote/resources/app/lib/main-app.js:20:16)`. It's an alert message without the main window visible (so no devtools-screenshot), on closing the alert message it seems that the program windows pops up for a millisecond but is closed immediately again.

Maybe of note: I added a storage inside of a Dropbox folder.

**Comment by pkollitsch** [comment] 2018-01-25 08:19
Starting on command line displays the following traceroute in addition to the popup:

```
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/share/boostnote/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/usr/share/boostnote/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/usr/share/boostnote/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

```

**Comment by kazup01** [comment] 2018-01-25 15:01
Hi @pkollitsch , sorry for the inconvenience.
Is bug same as #1264?

**Comment by pkollitsch** [comment] 2018-01-25 15:30
Yes, it seems to be related. When I kill all boostnote processes via `killall -9 Boostnote` it starts afterwards. 

When closing Boostnote, the following processes stay alive:

```
12947 tty1     Sl+    0:01 /usr/share/boostnote/Boostnote
12951 tty1     S+     0:00 /usr/share/boostnote/Boostnote --type=zygote --no-sandbox
12976 tty1     Sl+    0:00 /usr/share/boostnote/Boostnote --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,23,74 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --gpu-vendor-id=0x10de --gpu-device-id=0x10c5 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --service-request-channel-token=E8248054D47BB43BCC6BE02BF060039E
12991 tty1     Sl+    0:01 /usr/share/boostnote/Boostnote --type=renderer --no-sandbox --primordial-pipe-token=5A8517CF1B424D073754B92CF69ABD34 --lang=en-US --app-path=/usr/share/boostnote/resources/app --node-integration=true --webview-tag=true --no-sandbox --enable-blink-features=OverlayScrollbars --enable-pinch --num-raster-threads=1 --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --disable-accelerated-video-decode --service-request-channel-token=5A8517CF1B424D073754B92CF69ABD34 --renderer-client-id=6 --shared-files=v8_natives_data:100,v8_snapshot_data:101

```

**Comment by patrick-iv** [comment] 2018-01-27 14:58
I get the same error on Ubuntu 17.10, however if I just leave the dialog for a minute or so, Boostnote will start automatically

**Comment by gooodmorningopenstack** [comment] 2018-01-27 21:54
Hello, same here. The main process `Boostnote` isn't terminated following the application exit on Linux. It's a bug related to version `0.8.20`, the `0.8.19` works fine.

**Comment by Redsandro** [comment] 2018-01-29 23:32
Same here. Linux Mint 18.3 Sylvia (AKA Ubuntu 16.04.3 Xenial).

The error message is not nice, but basically the app won't start if it's already started. I suspect that you have this on high resolution screens, because it's easy to miss the icon in the task bar.

![image](https://user-images.githubusercontent.com/1702193/35540172-faba1358-0554-11e8-8d49-da9e83b78c15.png)

See https://github.com/BoostIO/Boostnote/issues/1479

**Comment by vangourd** [comment] 2018-02-01 15:05
+1 Same Issue here on Ubuntu Gnome 17.10. `killall Boostnote` successfully kills off the process allowing re-open.

**Comment by pkollitsch** [comment] 2018-02-01 15:13
It seems the issue is connected to the screen manager (or what it is called). I reinstalled a computer with Ubuntu 17.10 and switched the session from "Wayland" to "X11" and this issue is not appearing anymore. On the Wayland installation it's occuring. 

Sorry, I don't know enough about the underlying system to deduct reason for this :)

**Comment by pkollitsch** [comment] 2018-02-01 15:16
only Ubuntu 17.10!

to change from wayland to x11:

- sudo vi /etc/gdm3/custom.conf
- uncomment the line WaylandEnable=false (remove the # in the beginning)
- reboot

Ubuntu 18.04 will come with x11 as default session.

**Comment by gooodmorningopenstack** [comment] 2018-02-01 19:14
You don't necessarily need to edit Gnomes config files, on the login prompt when you type your password, just press the settings wheel just under the password field.

You can choose Wayland or Xorg and even Gnome or Gnome Classic.

**Comment by pkollitsch** [comment] 2018-02-02 02:43
I am not sure what I did differently in my installation, but the settings icon was not available on my login screen and a further search led to the custom.conf-"hack". But you are right. If it's there use it and nothing bad happens :)

**Comment by rmdwirizki** [comment] 2018-02-03 13:36
I got the same problem on manjaro (arch). The error showed if I close the app using the close button on the menu bar.

![selection_010](https://user-images.githubusercontent.com/13674295/35767571-21907d30-0921-11e8-9ab7-4f6a76641d28.png). 

I have to follow up using `kilall -9` command to make it work again. But it's working fine if I close the app from cascading menu or use `ctrl+q`.

![menu_009](https://user-images.githubusercontent.com/13674295/35767569-12ea94f0-0921-11e8-9c04-3b7b7979e8f2.png)

**Comment by dersteps** [comment] 2018-02-21 08:47
I encountered a similar issue on Debian 8.10 using Cinnamon. I do not see any tray icon at all, by the way, but the Boostnote process stays alive after exiting the program, leading to the error message already stated above (when run from a terminal window):

```
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/share/boostnote/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/usr/share/boostnote/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/usr/share/boostnote/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
```
Mind that I do not see any visual error message, but simply a brief flash of a window being opened and closed again immediately.

I am not an experienced electron developer at all, but in lib/main-window.js, from line 43, I see code that prevents the window from being closed on OS X and Cinnamon sessions. It seems like the code is preventing the default event behaviour and simply hiding the window. If there's no tray icon as in my case, that leaves the application running and lost to the user if I'm not mistaken.

Hope that helps

**Comment by Flexo013** [comment] 2019-07-29 06:58
I suspect that this is no longer a problem in the latest version of Boostnote, mostly because #1264 is also fixed.

@davidsneighbour Could you confirm that this doesn't happen anymore?

**Comment by Flexo013** [comment] 2019-09-23 08:59
I'm closing this issue do to prolonged inactivity.

If you still are experiencing this problem then feel free to reopen this issue or create a new issue with all the relevant information.

**Closed by Flexo013** 2019-09-23 08:59 UTC
Labels: bug :bug:, level 3 :exclamation::exclamation:, needs more info :information_source:

**Comment by davidsneighbour** [comment] 2019-09-23 12:11
Sorry, I didn't found this issue to comment until now. And yes, it's working now.

**Comment by Flexo013** [comment] 2019-09-25 23:33
Thanks for the update!
