### ISSUE TITLE
Can't paste image next to code blocks

### ISSUE THREAD

**Issue by cross-hello** [BoostIO/Boostnote#3561] opened 2020-04-29 05:33 UTC
# Current behavior

When cursor in line 4, I ***can't insert photo*** via ctrl +v. ( mouse also without power)
![image](https://user-images.githubusercontent.com/42733664/80563381-95cac500-8a1d-11ea-9ccd-b7ee9acefe8d.png)

# Expected behavior

Photo should be inserted normally.
# Steps to reproduce

# Environment

- Boostnote version:  0.15.3
- OS version and name:  Win7-64bit

**Comment by Flexo013** [comment] 2020-05-01 17:34
Confirmed on Win10 as well.

In the following note I have tried pasting an image between every set of code blocks. As you can see this only seems possible in 3 of the 11 places...
![image](https://user-images.githubusercontent.com/4507015/80826443-85b01280-8be2-11ea-92e6-9074dcd4f79d.png)

**Comment by arcturus140** [comment] 2020-05-01 22:33
duplicate of #3185

**Comment by Flexo013** [comment] 2020-05-07 20:32
Duplicate of #3185

**Closed by Flexo013** 2020-05-07 20:32 UTC
Labels: bug :bug:, level 1 :grey_exclamation:
