### ISSUE TITLE
UI not syncing with cloud storage

### ISSUE THREAD

**Issue by jasselin** [BoostIO/Boostnote#989] opened 2017-10-17 12:09 UTC
I am using Boostnote with files stored in a Synology CloudStation share. The files are changing on disk but I need to restart Boostnote for the UI to update the notes on screen. I assume the same behavior is present when using Dropbox.

Is this a known bug or is there a workaround?

**Comment by asmsuechan** [comment] 2017-10-17 13:13
Yes, I saw an issue regarding it. However, it's not supported for now because it takes a considerable amount of time to implement due to Boostnote's basic specifications such as data structure. There's a PR https://github.com/BoostIO/Boostnote/pull/926 regarding this but I'm not sure he's still working on it.

**Comment by fam4r** [comment] 2017-11-20 20:02
I can confirm that. I'm using Mega cloud sync: I need to restart Boostnote in the other PC to see changes in the UI.

**Comment by jbsmith7741** [comment] 2018-07-18 15:12
I'm seeing this same issue with using dropbox. a restart or reload is required to see any changes in the UI.

**Comment by Flexo013** [comment] 2019-08-18 18:14
This and #1790 are about the same feature. That one has funding so I'll be closing this one.

Btw you can do Ctrl+R to reload the files. It's not ideal, but better than rebooting the entire app.

**Closed by Flexo013** 2019-08-18 18:14 UTC
Labels: help wanted :sos:
