### ISSUE TITLE
Multi-level directory support

### ISSUE THREAD

**Issue by telleo** [BoostIO/Boostnote#1541] opened 2018-02-12 16:34 UTC
I wanna add a new direction in current direction . may support?

**Comment by islanddog** [comment] 2018-02-12 19:00
Each storage location can point to a different folder so essentially this can be utilized? If you mean in regards to Projects and not note taking other applications such as Sublime text can allow opening multiple files within a project.

**Comment by Flexo013** [comment] 2019-07-28 19:57
Duplicate of #125

**Closed by Flexo013** 2019-07-28 19:57 UTC
Labels: feature request :zap:
