### ISSUE TITLE
[bug]Text between two C++ code blocks is green

### ISSUE THREAD

**Issue by keddad** [BoostIO/Boostnote#3129] opened 2019-07-18 18:48 UTC
# Current behavior

Looks like normal text between two code blocks is painted as code if code language is c++
![image](https://user-images.githubusercontent.com/34062895/61482987-5ef25980-a98b-11e9-9b93-1649c3d80ebe.png)
[Example of such a note](https://gist.github.com/keddad/0bd36c467513d4596f1918debdff6176)

# Expected behavior
Text between code blocks shouldn't be colored

# Steps to reproduce

1. Write two blocks of code, specify the language as c++
2. Write some text between them 
3. Text is now green like the code!

# Environment

- Version : 0.11.17
- OS Version and name : Ubuntu 19.04 x86_64

**Comment by arcturus140** [comment] 2019-07-19 11:34
@keddad are you referring to the markdown editor or the rendered output?

**Comment by keddad** [comment] 2019-07-19 13:02
> @keddad you are referring to the markdown editor syntax highlighting, right?
> 
> I can replicate the issue (Ubuntu 16.04) using Editor Theme `duotone-light`.

Yep

**Comment by Flexo013** [comment] 2019-07-21 15:14
Duplicate of: https://github.com/BoostIO/Boostnote/issues/2639

**Closed by Flexo013** 2019-07-21 15:14 UTC
Labels: investigating :microscope:
