### ISSUE TITLE
right-to-left (rtl) languages support

### ISSUE THREAD

**Issue by aakbar5** [BoostIO/Boostnote#3279] opened 2019-10-16 10:10 UTC
# Current behavior

Boostnote should support RTL languages too. Currently it does not rendered text correctly. please see snapshot below.
![rtl](https://user-images.githubusercontent.com/16612387/66909814-50a4ef80-f005-11e9-8dea-9512c9aa284d.png)

**Comment by Flexo013** [comment] 2019-10-18 07:24
Duplicate of #846

**Closed by Flexo013** 2019-10-18 07:24 UTC
