### ISSUE TITLE
v 0.11.10 not open in Ubuntu 18.10

### ISSUE THREAD

**Issue by AlexanderBelm** [BoostIO/Boostnote#2555] opened 2018-10-29 09:21 UTC
Boostnote 0.11.10 does not open in Ubuntu 18.10

**Comment by AlexanderBelm** [comment] 2018-10-29 14:38
I installed Ubuntu 18.10 and installed Boostnote v0.11.10. When I run
boostnote v0.11.10, it does not start.
Then I installed on ubuntu 18.10 booste v0.11.6 and it works!

пн, 29 окт. 2018 г. в 12:25, Nguyen Viet Hung <notifications@github.com>:

**Comment by ZeroX-DG** [comment] 2018-10-29 14:54
We are going to need more information about that, can you install v0.11.10 then run `boostnote` from the terminal and tell us what is the error printed on the terminal?

**Comment by AlexanderBelm** [comment] 2018-10-29 15:09
Segmentation fault (core dumped)

пн, 29 окт. 2018 г. в 17:56, Nguyen Viet Hung <notifications@github.com>:

**Comment by crakoucas** [comment] 2018-10-29 21:36
Same issue => #2483

You need to wait the next release if #2484 will merge or

1. Clone the repo
2. Change electron to V3.0.3 in the package.json file
3. Build your own  Boostnote with Grunt Build

**Comment by Redsandro** [comment] 2018-10-30 20:59
Duplicate of #2483. @AlexanderBelm would you be so kind as to close this issue?

**Comment by synsa** [comment] 2018-10-31 02:44
Having the same issue on a fresh install of Kubuntu 18.10.

`Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic`
Kernel:	Linux 4.18.0-10-generic x86_64

**Closed** 2018-10-31 13:42 UTC
Labels: investigating :microscope:
