### ISSUE TITLE
[BUG] HTML Export invalid german umlauts

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#1460] opened 2018-01-25 10:42 UTC
By using german Umlauts like äöü the preview in boostnote is working fine.

![grafik](https://user-images.githubusercontent.com/3670907/35384167-bc1e5750-01c4-11e8-83ba-c3af27aec318.png)

But the HTML Export is broken:
![grafik](https://user-images.githubusercontent.com/3670907/35384197-d5117d6e-01c4-11e8-80f9-599c4efd658c.png)

**Comment by mirsch** [comment] 2018-03-07 00:02
duplicate of #1624 fixed by #1639

**Closed** 2018-03-07 00:53 UTC
