### ISSUE TITLE
Tags of trashed notes still considered under tags, but note not shown

### ISSUE THREAD

**Issue by sharif1093** [BoostIO/Boostnote#2836] opened 2019-01-26 18:25 UTC
# Current behavior

When a note with tags is trashed, its tags are still considered under the "Tags" pane. But when we click on those tags the note is not shown.

![trashed_tags](https://user-images.githubusercontent.com/10884607/51791178-0e810880-216d-11e9-87d8-173600eced27.png)

# Expected behavior

Tags of trashed notes not to be shown under the "Tags" pane.

# Steps to reproduce

1. Create a new note.
2. Add some example **unique** tags to it.
3. Delete the note.
4. Check the "Tags" pane. You should see the tags you added there.
5. Click on them.

# Environment

- Version: 0.11.13
- OS Version and name: Ubuntu 16.04 Xenial

**Comment by ZeroX-DG** [comment] 2019-01-27 09:54
In my case, the tag only appears when I restart the app. Thank @sharif1093 for reporting this.

**Comment by dredav** [comment] 2019-02-23 07:56
@sharif1093 I can also only reproduce this issue at the startup like @ZeroX-DG. Can you update boostnote to the current Version (0.11.15) and try to reproduce it?
You need to do a manual update since the autoupdate procedure was broken at 0.11.13.

**Comment by sharif1093** [comment] 2019-02-23 17:11
@dredav thanks for addressing this issue. Yes I have to restart as well to see the deleted note's tags.

**Comment by Flexo013** [comment] 2020-06-27 13:26
Fixed in the current version of Boostnote Legacy.

**Closed by Flexo013** 2020-06-27 13:26 UTC
Labels: bug :bug:
