### ISSUE TITLE
Collaborative editing

### ISSUE THREAD

**Issue by derekantrican** [BoostIO/Boostnote#3524] opened 2020-03-18 04:52 UTC
[This is a far-future suggestion]

It would be great to support collaborative editing on notes. Microsoft's Fluid Framework might be a good thing to look into:

Article: https://www.theverge.com/2019/11/4/20942031/microsoft-fluid-framework-office-web-preview
Public preview: https://fluidpreview.office.net/unauth

**Comment by Flexo013** [comment] 2020-03-18 19:24
Duplicate of #1829

**Closed by Flexo013** 2020-03-18 19:24 UTC
