### ISSUE TITLE
Additon of Export error

### ISSUE THREAD

**Issue by cross-hello** [BoostIO/Boostnote#3565] opened 2020-05-02 04:27 UTC
# Current behavior

The problem of exporting error of myself may be geting photo which  have lost.
So this link:

- ![missing.png]\(**:storage**/13205c21-b3eb-4ce5-b7d0-ebd3c3cf3dfe\29d9f792.png)

which had lost will *make a export error*(callback funtion error).
![Before-Operation](https://user-images.githubusercontent.com/42733664/80854958-fdc41a00-8c6e-11ea-90e6-dcbb9e292fc6.png)

But if I delete *any part* of keyword **: storage**, like "**:**":
- ![missing.png]\(**storage**/13205c21-b3eb-4ce5-b7d0-ebd3c3cf3dfe\29d9f792.png).

I could export a file with a empty photo link.
(Then we could add the photo link afterward manually = o = )
![After-operation](https://user-images.githubusercontent.com/42733664/80855002-8ba00500-8c6f-11ea-9e08-a1a4d435fbf1.jpg)

# Environment

- Boostnote version:  0.15.3
- OS version and name: Win7-64bits

**Comment by Flexo013** [comment] 2020-05-07 20:30
Duplicate of #3262

**Closed by Flexo013** 2020-05-07 20:30 UTC
