### ISSUE TITLE
HTML code blocks copied/pasted from HTML pages not converted to Markdown format correctly

### ISSUE THREAD

**Issue by machetto** [BoostIO/Boostnote#2913] opened 2019-03-05 22:52 UTC
# Current behavior

Copy/pasting code blocks (for example from [this page](https://www.dionach.com/blog/active-directory-password-auditing-part-2-cracking-the-hashes)) give parse errors in the note:

![image](https://user-images.githubusercontent.com/4196380/53842954-0ed6b400-3ff5-11e9-9b77-e7407d530c9c.png)

When text is copied/pasted from an HTML page to a new note, [(for example)](https://www.dionach.com/blog/active-directory-password-auditing), the note will contain just text, not Markdown code to correctly render code blocks.

# Expected behavior

The note's text should have code blocks prepended/appended with "```" strings to be rendered correctly.

# Steps to reproduce

Copy/paste any HTML page that contains code blocks

**Comment by arcturus140** [comment] 2019-03-06 00:24
to solve this problem you should change the latex delimiter to something different.

**Comment by machetto** [comment] 2019-03-06 21:51
And if I do this and then when I paste some other HTML text have another parsing error? Should I change some settings again?

I think it would be better if ```<pre>``` taged text is enveloped with three "`" characters in the note.

**Comment by RichardWPerrott** [comment] 2019-10-06 00:31
Indeed, my annoyance, is HTML links are broken by incorrect Markdown quoting for pasted page content, thus pointless editing to fix them.
# Current behavior
`abstract [Optional](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html "class in java.util")<[CookieHandler](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/CookieHandler.html "class in java.net")>`

# Expected behavior
Only quote text around link, never quote around link target, () part, and quoting maybe pointless/incompatible around the label, [] part, too.
`abstract`[HttpClient.Redirect](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.Redirect.html "enum in java.net.http")

# Steps to reproduce
Open (https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html) in a browser, select all, copy the content, then paste into a new Markdown Note in Boostnote.

# Environment
- Version : 0.12.1
- OS Version and name : Microsoft Window 10 Professional

**Comment by Flexo013** [comment] 2019-10-08 09:35
@RichardWPerrott With your steps to reproduce I just get a normal note with no strange linking behavior:

![image](https://user-images.githubusercontent.com/4507015/66383986-34c69b80-e9be-11e9-9a5e-2b118a0f2ba3.png)

The current behavior you mention also seems to work as expected:

![image](https://user-images.githubusercontent.com/4507015/66384130-76574680-e9be-11e9-8985-b9c9ca3d146b.png)

Adding quotes around the entire line does also yield in expected Markdown behavior:

![image](https://user-images.githubusercontent.com/4507015/66384599-56745280-e9bf-11e9-86ca-9cb31581bf32.png)

![image](https://user-images.githubusercontent.com/4507015/66384718-8e7b9580-e9bf-11e9-8eba-fc0dd5eb652e.png)

Could you provide the Markdown file that has wrong behavior for you?

**Comment by RichardWPerrott** [comment] 2019-10-09 04:07
I tried to paste a file but got a puzzling "We don't support that file type" banner, even with Shields-off in Brave browser.  Anyhow the image with line 3 shows incorrect MD escaping (left side) generated by the BoostIO HTML paste translation; like the original page, the linked URL should not be visible, via correct MD escaping.
This is quite annoying because I like to copy a lot of static HTML pages into BoostIO, for searchable reference and to cut browser window clutter, and prefer not to have to waste time fixing lots of flawed link translation.

**Comment by Flexo013** [comment] 2019-10-09 13:52
After checking #923 it seems that the current version 0.12.1 does not yet support the importing of (static) HTML pages. Therefore the behavior of pasting HTML content is undefined.

If you are already using a 0.13.0 pre-release build (of master) then ignore my previous statement and feel free to create a new github issue mentioning that the importing feature needs improvement.

Looking at the page's source code the behavior seems correct:
```html
<code>abstract <a href="../../../../java.base/java/util/Optional.html" title="class in java.util">Optional</a>&lt;<a href="../../../../java.base/java/net/CookieHandler.html" title="class in java.net">CookieHandler</a>&gt;</code>
```
This specifies the end and start of a code block. Which are properly transferred to the correct location in Markdown.

This is simply a difference of how code (blocks) work in HTMl vs Markdown.

**Closed** 2019-10-20 14:50 UTC
Labels: bug :bug:, needs more info :information_source:
