### ISSUE TITLE
Dark theme is gone in Boostnote 0.11.17

### ISSUE THREAD

**Issue by gerroon** [BoostIO/Boostnote#3052] opened 2019-06-02 05:16 UTC
Hi

I was using Boostnote 0.11.15 and I set everything to dark theme, it was all working fine including syntax highlighting in the markdown notes.  I upgraded to Boostnote 0.11.17 now neither editor nor the rendered view of the markdown text is dark, all I get black text over white background, even so i also lost the syntax highlighting of all my python code.

The UI retained the dark theme btw. 

I am using it on Win 10

EDIT: I went back to 0.11.15 and everything works again, so something is a bit fishy with the latets version it seems.

**Comment by MayakoLyyn** [comment] 2019-06-02 13:10
Came here to post the exact same thing. Also on Windows 10, latest updates applied.

**Comment by zzxxhhzxh** [comment] 2019-06-02 16:09
It is a bug from 0.11.17, you can temporarily solve it by the following:

Edit `\boost\app-0.11.17\resources\app\compiled\main.js`

Find :
	      path: path.join(directory.split(/\//g).slice(-3).join('/'), file),

Changed to:
	      path: path.join(CODEMIRROR_THEME_PATH, file),

**Comment by Exojay** [comment] 2019-06-02 18:55
From what I've seen, all of the color schemes except for the Default light editor scheme is missing.

**Comment by AWolf81** [comment] 2019-06-02 19:46
Yes, versions 0.11.16 & 0.11.17 got an issue with theming.

Should be fixed with PR #3048.

**Comment by humberto-garza** [comment] 2019-06-03 17:41
Same! I had to rollback to v0.11.15 (https://github.com/BoostIO/boost-releases/releases)

**Comment by payacoub** [comment] 2019-06-04 11:36
Same here; although the themes "Solarized Dark / Light" work on my side

**Comment by atezhill** [comment] 2019-06-05 06:42
> It is a bug from 0.11.16, you can temporarily solve it by the following:
> 
> Edit:
> `\boost\app-0.11.17\resources\app\compiled\main.js`
> 
> Find:
> `path: path.join(directory.split(/\//g).slice(-3).join('/'), file),`
> 
> Changed to:
> `path: path.join(CODEMIRROR_THEME_PATH, file),`

it works

**Comment by humberto-garza** [comment] 2019-06-28 16:03
> It is a bug from 0.11.16, you can temporarily solve it by the following:
> 
> Edit:
> `\boost\app-0.11.17\resources\app\compiled\main.js`
> 
> Find:
> `path: path.join(directory.split(/\//g).slice(-3).join('/'), file),`
> 
> Changed to:
> `path: path.join(CODEMIRROR_THEME_PATH, file),`

Workaround confirmed in windows!

**Comment by Flexo013** [comment] 2019-07-17 20:51
Will be fixed in the next release v0.12.0.

https://github.com/BoostIO/Boostnote/pull/3048 (merged)

**Closed by Flexo013** 2019-07-17 20:51 UTC
Labels: Level 1: Partially damaged, bug :bug:

**Comment by Flexo013** [comment] 2019-08-29 11:29
@aprather51 What OS are you running on? Have you tried any of the fixes mentioned in this thread?

**Comment by aprather51** [comment] 2019-08-29 14:45
SOLVED: I had to wipe completely clean the old version of Boostnote (v0.11.xx) inside Window 10's and reinstall everything as original. Now I can see "Interface Theme" appear in preference. 

On other hand, I just want to sharing my opinion... Naming "Interface Theme" probably isn't good idea for sake of user experience. How about "Theme" instead?

Thanks for replying back

**Comment by Flexo013** [comment] 2019-08-29 17:27
@aprather51 You're welcome.

The reason for Interface Theme is because there are multiple things that can be themed, such as your editor and code blocks. These have separate themes from the Interface Theme, thus simply calling it Theme would be confusing as it doesn't mention the theme of what you are changing.
