### ISSUE TITLE
[feature request] Multilevel catalogue

### ISSUE THREAD

**Issue by lqzhgood** [BoostIO/Boostnote#2932] opened 2019-03-18 09:18 UTC
# Current behavior
Boostnote now has only one level catalogue .
![qqq](https://user-images.githubusercontent.com/9134671/54519300-291f7300-49a1-11e9-9144-c90c80c98d15.jpg)

# Expected behavior

Add Multilevel catalogue would be better.
Like  
- System
  - Linux
     - openwrt
     - centos
   - Windows

# Environment
- Version : 1.7.9.0
- OS Version and name : Windows 10

**Comment by Diomas** [comment] 2019-03-19 05:21
duplicate of https://github.com/BoostIO/Boostnote/issues/586

**Closed** 2019-07-17 21:24 UTC
Labels: duplicate :no_entry_sign:
