### ISSUE TITLE
[Feature Proposal] Display date of task completion

### ISSUE THREAD

**Issue by matthieu-rolland** [BoostIO/Boostnote#2286] opened 2018-08-11 10:01 UTC
Hello,

I would like to see the date and time of completion of my tasks, displayed at the same place, just like it's done in the plaintask plugin for SublimeText...  but in the local language for more convenience.

Here is what I did: 

<img width="434" alt="capture d ecran 2018-08-11 a 11 39 04" src="https://user-images.githubusercontent.com/1784781/43990620-1631db06-9d5e-11e8-8c5b-d3aefa17dfc0.png">

I'm not sure if I'm the only one interested in this.... here is my pull request anyaway, just in case some other people might like it:

https://github.com/BoostIO/Boostnote/pull/2285

**Comment by modmod24** [comment] 2018-09-11 21:18
duplicate of #1438.

I like this implementation more than the current strike-through (v0.11.9).

**Comment by Flexo013** [comment] 2019-08-18 20:25
Duplicate of #1438

**Closed by Flexo013** 2019-08-18 20:25 UTC
Labels: feature request :zap:
