### ISSUE TITLE
Support searching text for markdown preview panel.

### ISSUE THREAD

**Issue by srcdes** [BoostIO/Boostnote#3267] opened 2019-10-08 02:07 UTC
# Current behavior

Can't search text when markdown preview pane is displayed only.

<img width="1377" alt="스크린샷 2019-10-08 오전 11 01 54" src="https://user-images.githubusercontent.com/32840866/66361903-9802fe80-e9bb-11e9-98f9-958bb06a69e3.png">

Searching feature is supported only when editor pane is displayed.

<img width="1377" alt="스크린샷 2019-10-08 오전 11 02 23" src="https://user-images.githubusercontent.com/32840866/66361925-b832bd80-e9bb-11e9-8b34-0d9e62974002.png">

# Expected behavior

Search text bar should be displayed within not only text editor pane, but also preview pane.

# Steps to reproduce

1. Open markdown file.
2. Toggle to markdown preview pane **only**
3. Can't search text in the file.

# Environment

- Version : 0.12.1
- OS Version and name : macOS Mojave 10.14.6

**Comment by Flexo013** [comment] 2019-10-08 07:31
Duplicate of #2625 

I have added the details from this issue to that other one, as the other issue could use some more elaboration. Thanks for the provided info!

**Closed by Flexo013** 2019-10-08 07:31 UTC
