### ISSUE TITLE
Support outlines/TOC in preview

### ISSUE THREAD

**Issue by codito** [BoostIO/Boostnote#1109] opened 2017-11-11 12:07 UTC
### Scenario
An outliner (e.g. clickable list of headings in a doc) in preview mode can help navigate sections in a long document easily. I use boostnote for taking book notes. Currently editing a ~1500 lines doc with tens of chapters/sections, could save a bunch of keystrokes with this functionality available :)

### Example
Here are a few example screenshots of similar idea in the wild.

1. VoOM outliner for VIM with markdown
![voom outliner example](https://vim-voom.github.io/pics/voom_voomhelp.png)

2. Typora editor
![typora editor example](https://typora.io/img/windows/screen2.png)

**Comment by kazup01** [comment] 2017-11-11 16:39
Hi @codito, thank you for your awesome suggestion! I also want it.
I made a mockup on a trial basis, what do you think about it?

![tocidea](https://user-images.githubusercontent.com/8602615/32691393-4de8c8d8-c74a-11e7-8682-3cc0bdc915a6.png)

**Comment by codito** [comment] 2017-11-12 05:49
@kazup01 thanks for quick response. Mockup looks great!

Will the sidebar be optionally visible based on user action (may be a hotkey)? This way if anyone prefers a editor-only view (for distraction free writing), they can hide it. I like the idea of indenting sub headings, it looks neat.

**Comment by lpld** [comment] 2018-01-02 20:32
This would be a great addition. For now, I can't find any way to navigate within a note, there is even no search in preview (or did i miss something?)

**Comment by Flexo013** [comment] 2019-07-28 17:18
This will probably be fulfilled by this new feature from this issue: #3172

**Comment by Flexo013** [comment] 2019-08-21 09:39
Duplicate of #2294 (which has funding)

**Closed by Flexo013** 2019-08-21 09:39 UTC
Labels: feature request :zap:
