### ISSUE TITLE
Hierarchical note structure

### ISSUE THREAD

**Issue by DictumMortuum** [BoostIO/Boostnote#2723] opened 2018-12-19 09:54 UTC
Hello,

I don't know if this is possible with the current implementation of boostnote, however, do you think that it would be possible to create a hierarchical note structure like [cherrytree](https://cdn.portableapps.com/CherrytreePortable.png)?

Regards,
Dimitris

**Comment by ZeroX-DG** [comment] 2018-12-20 15:35
This is a common feature request but it won't be implemented in the current version. The dev team is working on a rewrite version of Boostnote and this feature will be available there.

**Comment by kwendenarmo** [comment] 2019-01-06 18:16
It would be good if they were not only hierarchical notes, but also hierarchical folders. It should not be complicated to implement, since the folders are virtual.

**Comment by jcotton42** [comment] 2019-02-14 18:02
Something along the lines of OneNote's hierarchy (notebook -> section group -> section -> page -> subpages) would be great, though admittedly a bit complicated

**Comment by Kimi-Arthur** [comment] 2019-06-05 15:23
This is a great feature I'm longing for in Boostnote. It will make the whole thing much more intuitive.

Not sure if I'm oversimplifying things too much. But from understanding basically this is a folder viewer + note viewer. Would also like to help out if anything can make this feature available sooner. Thanks!

**Comment by DictumMortuum** [comment] 2019-06-06 07:07
I recently switched to Notable mainly because of this feature!

**Comment by hlascelles** [comment] 2020-01-18 18:25
This is now supported it seems.

![image](https://user-images.githubusercontent.com/299102/72668537-ecd4fd00-3a1f-11ea-82a7-41e05b234693.png)

**Comment by Flexo013** [comment] 2020-01-19 14:38
Duplicate of #125

**Closed by Flexo013** 2020-01-19 14:38 UTC
Labels: feature request :star2:
