### ISSUE TITLE
Can't scroll through list of folders after updating

### ISSUE THREAD

**Issue by kahboom** [BoostIO/Boostnote#3500] opened 2020-02-26 14:44 UTC
# Current behavior

I'm unable to scroll through the list of folders on the left hand menu after updating Boostnote a few days ago (I have a lot of folders). I have a general idea of what it might be, but not sure how to resolve it.

Console shows the following error:
`Failed to load resource: net::ERR_FILE_NOT_FOUND file:///Applications/Boostnote.app/Contents/Resources/app/lib/quiver-image-url/BF7ACB6FB623C1C5034EE6F27CAE1BFC.png`

And similar `GET file:///Applications/Boostnote.app/Contents/Resources/app/lib/quiver-image-url/9EE646FFAB71107D1A11407BE52F33A5 net::ERR_FILE_NOT_FOUND`

How can I find what note is referencing this image path, so that I can delete/modify it? Assuming that's what is causing the issue. I imported files from Quiver a long time ago, so I'm a bit confused if that is what is causing it.

And there's also a seemingly minor warning: `DevTools failed to parse SourceMap: file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/@rokt33r/js-sequence-diagrams/dist/sequence-diagram.js`

Tried `ctrl + r` and it didn't appear to  fix it. :/

# Expected behavior

It should allow users to scroll through a list of folders on the left hand side when the screen height is not long enough.

# Environment

- Version : 0.15.0
- OS Version and name : macOS Catalina

**Comment by tIsGoud** [comment] 2020-02-26 19:19
I have the exact same problem ...

**Comment by dogfish182** [comment] 2020-02-27 17:18
same here. had to switch over to tag browsing.

**Comment by Flexo013** [comment] 2020-02-27 18:17
Duplicate of #3486

**Closed by Flexo013** 2020-02-27 18:17 UTC
