### ISSUE TITLE
testing 0.11.9-pre.1

### ISSUE THREAD

**Issue by modmod24** [BoostIO/Boostnote#2316] opened 2018-08-21 02:03 UTC
hello, I just installed the latest pre-release for testing and I am experiencing some problems. 

1. it is significantly slower now taking almost 2 seconds to display a note
2. task lists are no longer working in full view
3. toggle mode is not working when clicking into the text body (I did not lock the view)

# Environment

- Version : 0.11.9-pre.1
- OS Version and name : 16.04 Ubuntu

**Comment by Rokt33r** [comment] 2018-08-21 18:54
> it is significantly slower now taking almost 2 seconds to display a note

It seems to be slow when opening snippet note.

**Comment by Rokt33r** [comment] 2018-08-21 18:57
@ZeroX-DG Could you help me?

**Comment by ZeroX-DG** [comment] 2018-08-22 03:35
Yes, I'm working on it

**Comment by ZeroX-DG** [comment] 2018-08-22 07:31
Note:
- The first bug occurred due to the library: https://github.com/podefr/react-debounce-render used in the PR: https://github.com/BoostIO/Boostnote/pull/2074. I haven't found this exact why that library is the cause but by removing it, the first bug disappeared.
- The second bug occurred due to that same library in the first bug. That library create a higher component so we can't access the function in the original component. The bad news is that library doesn't create an easy way to access the original component so we have to dig deep into the returned component to access it which make the code....you get the point
- I didn't understand how to reproduce the 3rd bug, @modmod24 can you show me how?

**Comment by modmod24** [comment] 2018-08-22 08:54
@ZeroX-DG 

In 0.11.8 you were able to enter editor view by left-clicking into the note: 
![before](https://user-images.githubusercontent.com/25648628/44453458-ff5fc280-a5f0-11e8-85a1-75bf15315ee2.gif)

In 0.11.9-pre.1 this feature is no longer supported, if I click on it, nothing happens:
![after](https://user-images.githubusercontent.com/25648628/44453457-ff5fc280-a5f0-11e8-88eb-e17b0c8321ae.gif)

**Comment by ZeroX-DG** [comment] 2018-08-22 08:57
Oh then I the 3rd issue has the same cause as the 2nd issue.

**Comment by sosukesuzuki** [comment] 2018-08-23 11:11
Note: 
- 1st issue:
  + [react-debounce-render](https://github.com/podefr/react-debounce-render) causes delay in a note display. I use it to improve the delay in displaying notes. However, I think that we should revert to not use this library to fix bugs. (The reversing should not cause fatal problems.)

- 2nd & 3rd issues
  + Thees seems to be caused by `react-debounce-render`. However, I can not find out why yet currently...:bow:
  + (Viewed from Elements of the developer tool, the style of `CodeEditor` and `MarkdownPreview` seems to be crazy.)

**Comment by ZeroX-DG** [comment] 2018-08-23 11:58
@sosukesuzuki The 2nd & 3rd issues is caused by `react-debounce-render` as the library create a higher order component and wrap the original component ([code](https://github.com/BoostIO/Boostnote/pull/2074/files#diff-15e7f898eb1b252e0e2a285a91f1a2ec)). Therefore, in some component, they can't access the original component method such as [`reload`](https://github.com/max-buranbaev/Boostnote/blob/51e836f32ad43e92025aa6140d71654762504ec3/browser/components/MarkdownEditor.js#L176)

**Comment by Rokt33r** [comment] 2018-09-01 08:00
I've reverted the previous PR, https://github.com/BoostIO/Boostnote/pull/2074/files
And, it seems to fix the bugs. I'll release v0.11.9-pre.2 tonight.

You can check it from the master branch too. I've already merged the fix.

Thank you all guys!! ❤️

**Closed by Rokt33r** 2018-09-01 08:00 UTC
Labels: bug :bug:
