### ISSUE TITLE
[bug]Wiki website is not up-to-date

### ISSUE THREAD

**Issue by Kan-** [BoostIO/Boostnote#2308] opened 2018-08-19 14:00 UTC
# Current behavior

Code snippet in article Wiki > Usage > 'TeX support' does not work as expected,

Screen shot: https://imgur.com/a/YsAhAtb

# Expected behavior

Snippet should look like on Wiki website.

# Environment

- Version :  Boostnote 0.11.8 with default settings
- OS Version and name : MS Windows 8.1

**Comment by modmod24** [comment] 2018-08-19 22:41
see #2252

**Comment by modmod24** [comment] 2018-08-19 22:52
I'd like to contribute. I already forked the wiki but it's a PITA to link it with the repo, couldn't figure it out :(

**Comment by modmod24** [comment] 2018-08-19 23:37
how about a boostnote notebook repo for the documentation?

![tex-support](https://user-images.githubusercontent.com/25648628/44314434-0fb94700-a411-11e8-9ff3-e660ac8b61e4.png)

**Comment by Flexo013** [comment] 2019-08-18 18:44
This was caused by the wrong delimiters. Should be fixed now, thanks!

**Closed by Flexo013** 2019-08-18 18:44 UTC
