### ISSUE TITLE
Unusably slow on large files

### ISSUE THREAD

**Issue by tan-90** [BoostIO/Boostnote#3479] opened 2020-02-19 22:32 UTC
# Current behavior
The editor is unusably slow at responding to mouse and keyboard when editing "large" files. When typing, it responds normally on the first 10 seconds or so, then it slows down to a point where each character typed takes 5 seconds to appear. Stopping typing and waiting until it caches up usually brings it back to normal, just to slow down again as soon as I start typing.
The file is about 2000 lines long. This does not happen on smaller files.

# Environment
- Version : 0.14.1
- OS Version and name: Windows_NT x64 10.0.18362

**Comment by Flexo013** [comment] 2020-02-24 19:18
Duplicate of #1770

**Comment by Flexo013** [comment] 2020-02-24 19:19
I recommend splitting your note up if possible as a temporary work-around.

**Closed by Flexo013** 2020-02-24 19:18 UTC
