### ISSUE TITLE
Long code lines do not wrap in PDF export

### ISSUE THREAD

**Issue by ThisIsIsaac** [BoostIO/Boostnote#3382] opened 2019-11-29 07:05 UTC
1. ~~Syntax highlighting is removed when exporting to PDF~~

This is how my code block looks in the preview

<img width="934" alt="Screen Shot 2019-11-29 at 16 04 20 PM" src="https://user-images.githubusercontent.com/49523965/69850161-fe244780-12c1-11ea-82eb-1c61c4cfd0bc.png">

But when exporting to PDF, code highilghting is gone
<img width="1625" alt="Screen Shot 2019-11-29 at 16 04 17 PM" src="https://user-images.githubusercontent.com/49523965/69850180-07151900-12c2-11ea-8230-6b746c9dc034.png">

2. **Code line longer than what can fit in a single line is chopped off in the PDF file**

**as you can see in the above two images**

3. ~~The theme isn't transferred to PDF.  As you can see, I'm using dracular, but when exported, the theme is removed in the PDF~~

**Comment by arcturus140** [comment] 2019-11-29 11:58
1. duplicate of #3125
3. duplicate of #3125
2. confirmed

**Comment by Flexo013** [comment] 2019-11-30 17:31
Duplicate of #2531

**Closed by Flexo013** 2019-11-30 17:31 UTC
Labels: bug :bug:, level 1 :grey_exclamation:
