### ISSUE TITLE
Old Boostnote (0.4) totally unusable

### ISSUE THREAD

**Issue by shoshievass** [BoostIO/Boostnote#3481] opened 2020-02-22 15:05 UTC
I was trying to mess with the keyboard shortcuts for copy/paste (to get the behavior described [here](https://github.com/BoostIO/Boostnote/issues/3449)) in Boostnote 0.4 and the program just totally stopped working. White screen with no ability to do anything. I downloaded the new 1.x version but it's not nearly as smooth as the old one and I couldn't import my directory structures from before.  I tried deleting and redownloading Boostnote 0.4 but it didn't help -- white screen of death and nothing else. I really love writing on (the old) Boostnote and so this really sucks.

**Comment by Flexo013** [comment] 2020-02-24 18:34
There are currently two different versions: Boostnote (old) and Boost Note.next (new). See https://boostnote.io/#OldApp

Are you sure you mean Boostnote 0.4? That one is from years ago. We just released 0.15.0 this week.

Could you check your recently edited notes and see if one of the .cson files has empty content? People have reported that issue in the past.

**Comment by shoshievass** [comment] 2020-02-26 14:08
Thanks for this! I think I mean 0.14, not 0.4 -- sorry about that. I've
updated to 0.15.0, but the problem is persisting -- there's no way to open
my preferences or open anything; the blank white page is the only thing I
can get no matter what I click on the menu. I checked the .cson files and
none of them are empty.. the issue seemed to be triggered when I messed
with the preferences in (I guess) unsupported way -- but now there's no way
to go back!

[image: image.png]

-Shosh

**Comment by shoshievass** [comment] 2020-02-26 14:08
Thanks for this! I think I mean 0.14, not 0.4 -- sorry about that. I've updated to 0.15.0, but the problem is persisting -- there's no way to open my preferences or open anything; the blank white page is the only thing I can get no matter what I click on the menu. I checked the .cson files and none of them are empty.. the issue seemed to be triggered when I messed with the preferences in (I guess) unsupported way -- but now there's no way to go back!

![image](https://user-images.githubusercontent.com/3093378/75352308-67363f80-585e-11ea-9258-4553bda7bab0.png)

**Comment by shoshievass** [comment] 2020-02-26 14:11
Here is what the console says from 'developer tools':
<img width="555" alt="image" src="https://user-images.githubusercontent.com/3093378/75352513-b8deca00-585e-11ea-9bc5-b301a83b85ea.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/3093378/75352552-c7c57c80-585e-11ea-8518-2adcc43a63a6.png">
<img width="558" alt="image" src="https://user-images.githubusercontent.com/3093378/75352580-d318a800-585e-11ea-984c-f3f20dc15976.png">
<img width="558" alt="image" src="https://user-images.githubusercontent.com/3093378/75352602-db70e300-585e-11ea-840c-89413add337a.png">

**Comment by Rokt33r** [comment] 2020-02-27 15:52
@shoshievass 
Could you share content of your preferences file to us? You can find it from `~/Library/Application Support/Boostnote/Preferences`.

**Comment by Flexo013** [comment] 2020-02-27 18:13
`C:\Users\Floris\AppData\Roaming\Boostnote` is the Windows equivalent.

You could also try backing up your notes, then uninstalling Boostnote, and then reinstalling it.

**Comment by shoshievass** [comment] 2020-02-27 18:44
> @shoshievass
> Could you share content of your preferences file to us? We need it to reproduce the problem. You can find it from `~/Library/Application Support/Boostnote/Preferences`.

Here it is:
{"brightray":{"devtools":{"preferences":{"Inspector.drawerSplitViewState":"{\"horizontal\":{\"size\":0,\"showMode\":\"OnlyMain\"}}","InspectorView.splitViewState":"{\"vertical\":{\"size\":0}}","console.sidebar.width":"{\"vertical\":{\"size\":0,\"showMode\":\"OnlyMain\"}}","console.sidebarSelectedFilter":"\"message\"","consoleShowSettingsToolbar":"false","currentDockState":"\"right\"","inspectorVersion":"26","panel-selectedTab":"\"console\"","releaseNoteVersionSeen":"11","sourcesPanelNavigatorSplitViewState":"{\"vertical\":{\"size\":0,\"showMode\":\"Both\"}}","sourcesPanelSplitViewState":"{\"vertical\":{\"size\":0,\"showMode\":\"Both\"},\"horizontal\":{\"size\":0,\"showMode\":\"Both\"}}","undefined-tabOrder":"{\"sources.scopeChain\":10,\"sources.watch\":20}"}},"media":{"device_id_salt":"fkeIl28UAXvi264rz1CuRA=="}},"partition":{"per_host_zoom_levels":{"6509286705118856911":{}}}}

**Comment by shoshievass** [comment] 2020-02-27 18:44
> `C:\Users\Floris\AppData\Roaming\Boostnote` is the Windows equivalent.
> 
> You could also try backing up your notes, then uninstalling Boostnote, and then reinstalling it.

I tried this and it didn't work :(

**Comment by ZeroX-DG** [comment] 2020-02-27 21:09
@shoshievass can you run this command in the `developer tools console` and post the output for us?
```
JSON.stringify(JSON.parse(localStorage.getItem("config")), null, 4)
```

**Comment by shoshievass** [comment] 2020-02-27 21:50
> @shoshievass can you run this command in the `developer tools console` and post the output for us?
> 
> ```
> JSON.stringify(JSON.parse(localStorage.getItem("config")), null, 4)
> ```

```
JSON.stringify(JSON.parse(localStorage.getItem("config")), null, 4)
"{
    "zoom": 1,
    "isSideNavFolded": false,
    "listWidth": 180,
    "navWidth": 200,
    "sortBy": {
        "default": "UPDATED_AT"
    },
    "sortTagsBy": "ALPHABETICAL",
    "listStyle": "SMALL",
    "amaEnabled": true,
    "autoUpdateEnabled": true,
    "hotkey": {
        "toggleMain": "Command + Alt + L",
        "toggleMode": "Command + Alt + M",
        "deleteNote": "Command + Shift + Backspace",
        "pasteSmartly": "Command + Shift + V + B",
        "prettifyMarkdown": "Command + Shift + F",
        "sortLines": "Command + Shift + S",
        "insertDate": "Command + /",
        "insertDateTime": "Command + Alt + /",
        "toggleMenuBar": "Alt"
    },
    "ui": {
        "language": "en",
        "theme": "default",
        "showCopyNotification": true,
        "disableDirectWrite": false,
        "defaultNote": "ALWAYS_ASK",
        "showMenuBar": true,
        "tagNewNoteWithFilteringTags": false,
        "confirmDeletion": false,
        "showOnlyRelatedTags": false,
        "showTagsAlphabetically": true,
        "saveTagsAlphabetically": false,
        "enableLiveNoteCounts": false
    },
    "editor": {
        "theme": "base16-light",
        "keyMap": "sublime",
        "fontSize": "14",
        "fontFamily": "Monaco",
        "indentType": "space",
        "indentSize": "2",
        "lineWrapping": true,
        "enableRulers": false,
        "rulers": [
            "80",
            "120"
        ],
        "displayLineNumbers": true,
        "matchingPairs": "()[]{}''\"\"$$**``~~__",
        "matchingTriples": "```\"\"\"'''",
        "explodingPairs": "[]{}``$$",
        "switchPreview": "BLUR",
        "delfaultStatus": "PREVIEW",
        "scrollPastEnd": false,
        "type": "SPLIT",
        "fetchUrlTitle": true,
        "enableTableEditor": true,
        "enableFrontMatterTitle": false,
        "frontMatterTitleField": "title",
        "spellcheck": true,
        "enableSmartPaste": true,
        "enableMarkdownLint": false,
        "customMarkdownLintConfig": "{\n  \"default\": true\n}",
        "prettierConfig": " {\n      \"trailingComma\": \"es5\",\n      \"tabWidth\": 4,\n      \"semi\": false,\n      \"singleQuote\": true\n    }",
        "deleteUnusedAttachments": true,
        "snippetDefaultLanguage": "Auto Detect"
    },
    "preview": {
        "fontSize": "14",
        "fontFamily": "Lato",
        "codeBlockTheme": "dracula",
        "lineNumber": true,
        "latexInlineOpen": "$",
        "latexInlineClose": "$",
        "latexBlockOpen": "$$",
        "latexBlockClose": "$$",
        "plantUMLServerAddress": "http://www.plantuml.com/plantuml",
        "scrollPastEnd": false,
        "scrollSync": true,
        "smartQuotes": true,
        "breaks": true,
        "smartArrows": false,
        "allowCustomCSS": false,
        "customCSS": "/* Drop Your Custom CSS Code Here */",
        "sanitize": "STRICT",
        "mermaidHTMLLabel": false,
        "lineThroughCheckbox": true
    },
    "blog": {
        "type": "wordpress",
        "address": "http://wordpress.com/wp-json",
        "authMethod": "JWT",
        "token": "",
        "username": "",
        "password": ""
    },
    "coloredTags": {},
    "language": "en",
    "theme": "default",
    "showCopyNotification": true,
    "disableDirectWrite": false,
    "defaultNote": "ALWAYS_ASK",
    "showMenuBar": true,
    "6b72fe34f4c420d66ae7": {
        "sortBy": "UPDATED_AT"
    },
    "tagNewNoteWithFilteringTags": false,
    "confirmDeletion": false,
    "showOnlyRelatedTags": false,
    "showTagsAlphabetically": true,
    "saveTagsAlphabetically": false,
    "enableLiveNoteCounts": false
}"
```

**Comment by ZeroX-DG** [comment] 2020-02-27 23:10
@shoshievass I think the hotkey `"pasteSmartly": "Command + Shift + V + B",` is causing the problem. If my theory is right then the command bellow should be able to fix your problem. Just run the command bellow in the `developer tools console` and restart Boostnote :+1: 

```
current_config = JSON.parse(localStorage.getItem("config"));current_config.hotkey.pasteSmartly = "Command + Shift + B";localStorage.setItem("config", JSON.stringify(current_config));
```

**Comment by shoshievass** [comment] 2020-02-27 23:19
> @shoshievass I think the hotkey `"pasteSmartly": "Command + Shift + V + B",` is causing the problem. If my theory is right then the command bellow should be able to fix your problem. Just run the command bellow in the `developer tools console` and restart Boostnote 👍
> 
> ```
> current_config = JSON.parse(localStorage.getItem("config"));current_config.hotkey.pasteSmartly = "Command + Shift + V";localStorage.setItem("config", JSON.stringify(current_config));
> ```

That worked! Thanks!

**Comment by ZeroX-DG** [comment] 2020-02-27 23:27
Glad to hear that @shoshievass :smile: the problem is because the library that we use doesn't like your hotkey `Command + Shift + V + B` so I changed it to `Command + Shift + V`. I'll see what I can do to prevent this from happening in the future. For now I'll close this issue.

**Closed by ZeroX-DG** 2020-02-27 23:27 UTC
Labels: question :question:
