### ISSUE TITLE
Render bug in version 0.11.8

### ISSUE THREAD

**Issue by weaming** [BoostIO/Boostnote#2224] opened 2018-07-20 06:12 UTC
![image](https://user-images.githubusercontent.com/10275711/42986089-d5a769d6-8c26-11e8-8c82-51a0c9f79d89.png)

The render result is not correct as you see.

**Comment by ZeroX-DG** [comment] 2018-07-20 06:26
Thank you for reporting, this is a duplicate of https://github.com/BoostIO/Boostnote/issues/2217

**Closed** 2018-07-23 16:44 UTC
