### ISSUE TITLE
Boostnote can't update itself

### ISSUE THREAD

**Issue by davidtimovski** [BoostIO/Boostnote#830] opened 2017-08-26 16:10 UTC
I'm on Windows 10 and when I open the app and it has an update I get the "Update found! Preparing to update..." notification 2 or 3 times usually and it never actually updates. I can leave the application open for the whole day and it won't update. Every time I turn it on I get the same notification. It's come to the point where I reinstall it whenever there's a new update.

Here's a screenshot of the Console:
![boostnote](https://user-images.githubusercontent.com/25406486/29743045-ecc0caee-8a89-11e7-91cf-a7d54f1a8761.png)

**Comment by kazup01** [comment] 2017-08-31 02:40
Hi @davidtimovski , sorry for inconvenient. Could you tell me your Boostnote version?

**Comment by thealexander90** [comment] 2017-09-07 08:25
Same here, Win10, version 0.8.9 and only the same fonts errors.
Just tried and at the bottom of the screen appeared "Last updated..." with current time but after checking the info window the version didn't change.

**Comment by kazup01** [comment] 2017-09-07 17:01
Hi @thealexander90 , thanks for your reporting!
I'm terribly sorry, could you install the latest version again? Even if you reinstall it, Boostnote's data will be taken over as it is.
https://boostnote.io/#download

P.S. I really want to go to Italy.

**Comment by thealexander90** [comment] 2017-09-07 17:32
Alright, tomorrow I'll try with a full reinstall.

P.S. Maybe we should switch country for a while ... :D

**Comment by thealexander90** [comment] 2017-09-08 07:44
Just tried "incremental" updates with two of the previous versions and I got every time the same problem.
I don't know if you already fixed this but I think the problem is in the url requested.

Example:
https://github.com/BoostIO/boost-releases/releases/download/v0.8.14/boost-0.8.13-delta.nupkg
This result in a 404.

Shouldn't the correct url be:
https://github.com/BoostIO/boost-releases/releases/download/v0.8.13/boost-0.8.13-delta.nupkg
( just changed the folder version )

I hope I'm not being too annoying about this problem since I don't even know if you already fixed it in the last version...

If you already fixed it in the last version ( 0.8.14 ) you can just ignore my ranting :)

**Comment by davidtimovski** [comment] 2017-09-09 13:55
@kazup01 Sorry for not replying, I was out of the country. My version is 0.8.12. The app hasn't successfully updated as of yet. I'll reinstall it again and hope for the best for future updates..

**Comment by kazup01** [comment] 2017-09-11 01:42
Thanks @davidtimovski for your replying! This font bug is fixed at #779.
And I'm terribly sorry for reinstall app. Thank you for your kindness!

**Comment by kazup01** [comment] 2017-09-24 04:31
I close this PR, but please reopen if you guys need. Thanks!

**Closed by kazup01** 2017-09-24 04:31 UTC

**Comment by horcrux2301** [comment] 2018-10-01 20:08
> This still happens as of today on Mac. Boostnote keeps telling me that a new update has been found ... preparing to update ..... but that never happens!

I am facing the same issue on MacOS High Sierra.
