### ISSUE TITLE
Storages are missing at startup

### ISSUE THREAD

**Issue by sahilseth** [BoostIO/Boostnote#1755] opened 2018-03-26 00:40 UTC
Each time I start boostnote on this machine -  the configured storages are gone, and have to be added again.

Interestingly, on a different machine storages stay, and don't need to be reconfigured. 
 
<img width="1221" alt="screen shot 2018-03-25 at 7 35 17 pm" src="https://user-images.githubusercontent.com/684975/37881927-db769158-3063-11e8-8717-41755d8a0d54.png">

**Comment by Rokt33r** [comment] 2018-03-26 02:06
It seems you moved the directory without unlink.

Please run `localStorage.clear()` in the console and restart the app. :)

**Comment by Rokt33r** [comment] 2018-03-26 02:07
And, I assume we have to handle this error.

**Comment by chufnagel** [comment] 2018-04-01 01:51
Having the same issue; can add new folders as storage, but can't re-add any of my old ones.
<img width="555" alt="screen shot 2018-03-31 at 9 49 12 pm" src="https://user-images.githubusercontent.com/927009/38169059-73a95870-352d-11e8-860f-acb561474ea1.png">

**Comment by Karrade7** [comment] 2018-04-01 09:41
I've run across the same bug. I've been using boostnote for a while and haven't run into this before.
I had boostnote open but at some point it must have crashed. When I re-loaded the storage was no longer mounted. I can't see to get any storage to stay mounted across restarts. if I run localStorage.clear() as suggested, the default storage gets mounted but thats also lost across restarts.
<img width="1440" alt="boostnote" src="https://user-images.githubusercontent.com/1933873/38171854-0f4c5872-353d-11e8-87af-6990b0552f9c.png">

**Comment by Rokt33r** [comment] 2018-04-01 09:45
@chufnagel @Karrade7 
Enter `localStorage.clear()` to the console and refresh the app.

**Comment by Karrade7** [comment] 2018-04-01 09:46
One more datapoint. 
When i try to re-add my originally created stprage mount which contains a boosnote.json file and a lot of notes I an uncaught error:
main.js:3656 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at file:///Applications/Boostnote.app/Contents/Resources/app/compiled/main.js:3656:19
    at Array.forEach (native)
    at data (file:///Applications/Boostnote.app/Contents/Resources/app/compiled/main.js:3633:21)
    at file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/redux/dist/redux.min.js:1:5926
    at s (file:///Applications/Boostnote.app/Contents/Resources/app/node_modules/redux/dist/redux.min.js:1:1820)
    at file:///Applications/Boostnote.app/Contents/Resources/app/compiled/main.js:61491:10
    at <anonymous>:null:null

<img width="1440" alt="boostnote-error2" src="https://user-images.githubusercontent.com/1933873/38171879-b995ba44-353d-11e8-9241-6b4174db2a2a.png">

**Comment by Karrade7** [comment] 2018-04-01 17:05
@Rokt33r  Thanks for your fast response. I tried localStorage.clear() but 
I got an undefined response. I also tried downgrading to the previous version and then upgrading. When I did that storage returned. However when I loaded my previous notes the storage disappeared. I'm guessing something is written to notes that is crashing.

Screen of undefined below.
<img width="1440" alt="undefined" src="https://user-images.githubusercontent.com/1933873/38175612-098f9514-357b-11e8-8751-5297ace6f5d9.png">

**Comment by Karrade7** [comment] 2018-04-01 17:08
BTW - this is what happens when I add a new storage.

<img width="1440" alt="new storage" src="https://user-images.githubusercontent.com/1933873/38175636-6e51226a-357b-11e8-83c1-ae4a8ae4207e.png">

**Comment by Rokt33r** [comment] 2018-04-02 05:58
Did you refresh the app?

**Comment by Karrade7** [comment] 2018-04-02 19:56
@Rokt33r . When you say refresh the app, do you mean something besides restarting it? I restarted it.

I think I found one of the issues though. There are some oddities in in the data being written.
One of the items that is fatal is that there is a note only with the following content:

`'content': ''`

When I add this to notes directory, boost note crashes.
I don't know what created it, but its creation date is from a day ago when I first had the issue. 
That's not the only issue. When I copy all my other notes back storage disappears again so some other note is fault. I'll have to go through them.

A few other oddities I noticed. I don't know if these are related:
Boostnote.json has an odd folder entry that has no key.
``` json
    {
      "color": "#E10051",
      "name": "Unknown 1"
    }
```


Some of my notes now have much longer file names. Example:
f7581908-8dd4-4637-86bd-e79939fad076.cson

But older notes have shorter filenames:
97f6ad41d8a6ba4a6aa5.cson


I will keep looking for the errant notes causing the crash.

BTW - I really love boostnote, so I'm happy to help as best as I can.

**Comment by Karrade7** [comment] 2018-04-02 20:13
Update:
I found two files with only the content field and it being empty as referenced above and here:
'content': ''

When I removed those files and copied my notes back everything loaded.
I'll look through my backups to see if there was real data in these notes that got overridden, but at minimum seems like there is a bug around better handling of malformed note files and potentially a bug creating these notes in the first place.

**Comment by urda** [comment] 2018-04-02 22:37
I may have also been impacted while reporting issue #1763 , but I do not have any logs or reproduction steps (as I did not do a deep dive on it).

I do recognize some of these errors here, and it was occurring when I was attempting to move notes between folders in the same storage *and* folders between storage locations.

**Comment by urda** [comment] 2018-04-02 22:39
Other than that I do not have any notes to report. If I can reproduce my (possibly this) storage issue again I'll have a full write up ready.

**Comment by bimlas** [comment] 2018-04-26 20:19
Sorry, I just typed wrong PR number.

**Comment by Flexo013** [comment] 2019-07-28 18:56
@sahilseth @urda Is this issue still present in the current version of Boostnote?

**Comment by urda** [comment] 2019-07-29 17:50
@Flexo013 I actually stopped using Boostnote for production uses at this time.

**Comment by Flexo013** [comment] 2019-07-30 09:47
Understandable.

I will close this issue for now since there is nobody who can reproduce it.

**Closed by Flexo013** 2019-07-30 09:47 UTC
Labels: bug :bug:, needs more info :information_source:

**Comment by eccelm** [comment] 2020-10-15 18:03
I tihnk my files were Local - I ran the localStorage.clear() 
Does this mean my notes are completely lost

**Comment by Flexo013** [comment] 2020-10-24 11:26
@eccelm I'm not entirely sure as to what that function does, but I suspect that you indeed cleared all your local storages... :(
