### ISSUE TITLE
White screen on start up

### ISSUE THREAD

**Issue by sssstar** [BoostIO/Boostnote#3232] opened 2019-09-01 09:09 UTC
正在写着突然就白屏了，卸载重装都没用
![image](https://user-images.githubusercontent.com/49156927/64074218-2c9e8080-ccdb-11e9-903a-0fee4351a0cb.png)

**Comment by sssstar** [comment] 2019-09-01 09:12
Don't know why the software's window is white.
Uninstalling reloading is useless.

**Comment by Flexo013** [comment] 2019-09-01 14:10
@sssstar Please provide all the information that was in the original template for creating an issue (in English). Otherwise we can't really help you.

**Comment by hikerpig** [comment] 2019-09-02 06:00
@sssstar Could you open the devtools ('View' -> 'Toggle Developer Tools') and see what's going wrong?

**Comment by XXXXXiang** [comment] 2019-09-07 15:44
@sssstar  Did you just type reserved word (keyword) like <a href> or something in your note?
I have found a bug that if you type <a href> after any word, then you will cause a white screen.
If you have done this before, find the file that you have typed (you can open them as a txt type file to check ), remove or edit (delete that keyword) that file.

**Comment by sssstar** [comment] 2019-09-25 09:36
```
TypeError: Cannot read property 'replace' of undefined
    at naughtyHRef (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65369:16)
    at sanitizeInline (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65340:16)
    at Array.<anonymous> (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65298:47)
    at Core.process (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\index.js:519:13)
    at MarkdownIt.render (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\index.js:539:36)
    at Markdown.render (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:34526:23)
    at MarkdownPreview.rewriteIframe (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:33357:41)
    at MarkdownPreview.componentDidMount (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:33220:13)
    at qi (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:130:198)
    at ui (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:133:320)
    at file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:377
    at unstable_runWithPriority (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react/umd/react.production.min.js:27:36)
    at Vc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:360)
    at Sc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:144)
    at Z (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:156:492)
    at Kc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:155:69)
    at ya (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:153:185)
    at Object.enqueueSetState (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:202:409)
    at DebouncedContainer.t.setState (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react/umd/react.production.min.js:20:433)
    at DebouncedContainer.<anonymous> (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:212388:21)
    at invokeFunc (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10333:23)
    at trailingEdge (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10382:18)
    at timerExpired (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10370:18)

Bg @ react-dom.production.min.js:117
react-dom.production.min.js:157 Uncaught TypeError: Cannot read property 'replace' of undefined
    at naughtyHRef (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65369:16)
    at sanitizeInline (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65340:16)
    at Array.<anonymous> (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65298:47)
    at Core.process (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\index.js:519:13)
    at MarkdownIt.render (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\index.js:539:36)
    at Markdown.render (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:34526:23)
    at MarkdownPreview.rewriteIframe (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:33357:41)
    at MarkdownPreview.componentDidMount (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:33220:13)
    at qi (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:130:198)
    at ui (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:133:320)
    at file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:377
    at unstable_runWithPriority (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react/umd/react.production.min.js:27:36)
    at Vc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:360)
    at Sc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:144)
    at Z (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:156:492)
    at Kc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:155:69)
    at ya (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:153:185)
    at Object.enqueueSetState (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:202:409)
    at DebouncedContainer.t.setState (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react/umd/react.production.min.js:20:433)
    at DebouncedContainer.<anonymous> (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:212388:21)
    at invokeFunc (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10333:23)
    at trailingEdge (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10382:18)
    at timerExpired (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10370:18)

DevTools failed to parse SourceMap: file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/@rokt33r/js-sequence-diagrams/dist/sequence-diagram.js
```

**Comment by sssstar** [comment] 2019-09-25 09:40
react-dom.production.min.js:117 TypeError: Cannot read property 'replace' of undefined
    at naughtyHRef (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65369:16)
    at sanitizeInline (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65340:16)
    at Array.<anonymous> (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65298:47)
    at Core.process (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\index.js:519:13)
    at MarkdownIt.render (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\index.js:539:36)
    at Markdown.render (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:34526:23)
    at MarkdownPreview.rewriteIframe (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:33357:41)
    at MarkdownPreview.componentDidMount (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:33220:13)
    at qi (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:130:198)
    at ui (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:133:320)
    at file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:377
    at unstable_runWithPriority (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react/umd/react.production.min.js:27:36)
    at Vc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:360)
    at Sc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:144)
    at Z (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:156:492)
    at Kc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:155:69)
    at ya (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:153:185)
    at Object.enqueueSetState (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:202:409)
    at DebouncedContainer.t.setState (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react/umd/react.production.min.js:20:433)
    at DebouncedContainer.<anonymous> (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:212388:21)
    at invokeFunc (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10333:23)
    at trailingEdge (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10382:18)
    at timerExpired (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10370:18)

Bg @ react-dom.production.min.js:117
react-dom.production.min.js:157 Uncaught TypeError: Cannot read property 'replace' of undefined
    at naughtyHRef (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65369:16)
    at sanitizeInline (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65340:16)
    at Array.<anonymous> (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:65298:47)
    at Core.process (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\index.js:519:13)
    at MarkdownIt.render (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\markdown-it\lib\index.js:539:36)
    at Markdown.render (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:34526:23)
    at MarkdownPreview.rewriteIframe (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:33357:41)
    at MarkdownPreview.componentDidMount (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:33220:13)
    at qi (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:130:198)
    at ui (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:133:320)
    at file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:377
    at unstable_runWithPriority (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react/umd/react.production.min.js:27:36)
    at Vc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:360)
    at Sc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:158:144)
    at Z (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:156:492)
    at Kc (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:155:69)
    at ya (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:153:185)
    at Object.enqueueSetState (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react-dom/umd/react-dom.production.min.js:202:409)
    at DebouncedContainer.t.setState (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/react/umd/react.production.min.js:20:433)
    at DebouncedContainer.<anonymous> (file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/compiled/main.js:212388:21)
    at invokeFunc (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10333:23)
    at trailingEdge (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10382:18)
    at timerExpired (C:\Users\Administrator\AppData\Local\boost\app-0.12.1\resources\app\node_modules\lodash\lodash.js:10370:18)

DevTools failed to parse SourceMap: file:///C:/Users/Administrator/AppData/Local/boost/app-0.12.1/resources/app/node_modules/@rokt33r/js-sequence-diagrams/dist/sequence-diagram.js

**Comment by hikerpig** [comment] 2019-09-25 10:10
@sssstar This bug is fixed by a47dac285, you can wait for next release, or try to fix your source file which contains `<a href>` as @XXXXXiang   describes

**Comment by sssstar** [comment] 2019-09-25 11:56
@hikerpig Thank you for your reply!

**Comment by Flexo013** [comment] 2019-09-25 23:30
Fixed by #3179

**Closed by Flexo013** 2019-09-25 23:30 UTC
Labels: needs more info :information_source:

**Comment by changyuanchn** [comment] 2020-01-19 07:48
is anyone know how to save my notes？I came across the same problem and cannot visit my notes before.

**Comment by hikerpig** [comment] 2020-01-19 08:00
@changyuanchn what is your os and version of boostnote ？

**Comment by Flexo013** [comment] 2020-01-19 14:29
@changyuanchn Feel free to make a new issue and reference this one with `#3232`. Since it is unlikely that the cause of this issue is the same as yours.

**Comment by changyuanchn** [comment] 2020-01-20 13:40
> @changyuanchn what is your os and version of boostnote ？

win10 + 0.1.2.0

**Comment by changyuanchn** [comment] 2020-01-20 13:42
> @changyuanchn what is your os and version of boostnote ？
os：win10
version: 0.1.2.0
![image](https://user-images.githubusercontent.com/5381386/72730928-81c92900-3bcd-11ea-9702-49b861e131ba.png)

I want to know how to save the file before, I cannot open that folder and seems lost all my notes int that folder, thanks!

**Comment by hikerpig** [comment] 2020-01-20 14:21
You seem to be using the developing new version of **new** boostnote,  it's not yet compatible with the current version yet (I guess).

You should open a new issue in the new repo.

**Comment by hikerpig** [comment] 2020-01-20 14:27
@changyuanchn  And also, please provide some error info to help us addressing the problem.
> Could you open the devtools ('View' -> 'Toggle Developer Tools') and see what's going wrong?

**Comment by changyuanchn** [comment] 2020-01-21 08:35
I download a new version (0.1.4.0) and install it. Then I can open that folder. thanks all. It seems that the bugs is fixed.

**Comment by KG16** [comment] 2020-07-26 17:03
I am on the latest version, still when I type ``` or paste code from internet, the screen goes blank.
![image](https://user-images.githubusercontent.com/16429717/88484939-00918b00-cf90-11ea-88a4-43e65966d11a.png)

**Comment by Flexo013** [comment] 2020-08-02 11:14
@KG16 Could you provide the version number? There are two Boostnote applications that work differently, so we need to know which one you are running.
