### ISSUE TITLE
Muliple Notebooks

### ISSUE THREAD

**Issue by archerindigo** [BoostIO/Boostnote#3049] opened 2019-05-31 02:51 UTC
# Current behavior

Currently there is only one notebook, a set of category and single level of notes within each category. It is enough if your notes are of single topic. However, if you have multiple irrelevant topics, it is not suitable to put them in a single view. For example, you have a set of programming notes and another set of school notes that you won't view them at the same time, putting them in the single notebook will make you hard to find the notes you want. Having separated notebooks would be a better idea.

# Expected behavior
Multiple notebooks may be achieved by allowing boostnote to switch and load a notebook at different storage location. Multiple boostnote instances (windows) loading notebooks at different locations respectively would also be nice.

# Steps to reproduce
It is a feature suggestion.

# Environment
It is a feature suggestion.

**Comment by archerindigo** [comment] 2019-06-18 11:21
I just found I can add different storage locations in Preferences -> storage. This can be treated as multiple notebooks. But still, multiple levels of notes within a category is still preferred.

**Comment by arcturus140** [comment] 2019-07-20 04:32
unfortunately search and filter are global

**Comment by arcturus140** [comment] 2019-07-20 04:40
multiple storage locations is already supported. feature requests such as #2097 can further improve context switching. maybe other suggestions or close this issue.

**Comment by Flexo013** [comment] 2019-07-21 14:23
Duplicate of: https://github.com/BoostIO/Boostnote/issues/2263

**Closed by Flexo013** 2019-07-21 14:23 UTC
Labels: feature request:zap:
