### ISSUE TITLE
Add Standard File backend

### ISSUE THREAD

**Issue by spott** [BoostIO/Boostnote#249] opened 2017-01-17 23:43 UTC
[Standard File](https://standardfile.org/models) is supposed to be a very simple encrypted file store for notes, with an emphasis on simplicity of format and features.

[Standard Notes](https://standardnotes.org) is their current benchmark notes application, however, it lacks some of the nice-to-have features of boostnote.  The two are similar enough, however, that it should be possible to make Boostnote use Standard File as a file store without too much difficulty.

**Comment by asmsuechan** [comment] 2017-02-06 22:45
Sorry for long absent @spott. Do you mean **Standard File importer** is helpful for you?

**Comment by spott** [comment] 2017-02-06 23:40
It would be nice to use it as a file store:  saving and syncing with the standard file service rather than on disk.

Similar to using dropbox or iCloud, just a different system.

**Comment by adrm** [comment] 2018-03-09 22:43
This is a duplicate of #874. I would love to have this feature!

**Closed** 2019-08-04 17:55 UTC
Labels: discussion :speech_balloon:, duplicate :no_entry_sign:, feature request :zap:
