### ISSUE TITLE
Export error when exporting all file types md\txt\html\pdf

### ISSUE THREAD

**Issue by nefusmzj** [BoostIO/Boostnote#3403] opened 2019-12-25 02:17 UTC
# Export error when exporting md\txt\html\pdf

Export error when exporting all types (md\txt\html\pdf)，ErrorBox show "Callback must be a function!"。

![export call back error](https://github.com/nefusmzj/ImageCache/raw/master/export.png)

![export call back error2](https://github.com/nefusmzj/ImageCache/raw/master/callbackerror.png)

# Environment

- Version : Boostnote 0.13.0
- OS Version and name : Windows10 x64 1809

Thank You

**Comment by Flexo013** [comment] 2019-12-27 12:17
Duplicate of #3262

**Closed by Flexo013** 2019-12-27 12:17 UTC
