### ISSUE TITLE
Reload notes if they changed on disk

### ISSUE THREAD

**Issue by pokidovea** [BoostIO/Boostnote#1203] opened 2017-11-29 08:54 UTC
I have two machines. Notes are stored in dropbox folder. When I add a note on machine1 I would like to see changes on machine2 without restarting the Boostnote application. Is it possible? Or if it is implemented, a bug takes place.

**Comment by Oylex** [comment] 2017-11-29 16:12
You can just reload the page (ctrl+R), but it's still a "restart".

I also save my notes on dropbox, but there is another problem than just reloading. If you have Boostnote open at 2 locations at the same time, it can corrupt the folder lists and the names are replaced by "Unknown" or something like that. Also, the last computer to update the file wins and the other loses it's changes.

Something else that I'm doing is having one particular storage location commited to GIT, with this I can share this storage location with people and we can never overwrite our changes, but we have to push/pull.

**Comment by mmueller** [comment] 2018-05-31 01:05
Yeah, uh, this is the thing that is promised on the homepage (boostnote.io) to new users. I'm surprised it doesn't actually work.

> _The note-taking app for programmers that focuses on markdown, snippets, and customizability.
Edit your code and wikis from anywhere._

This, plus the Android app not supporting file-level sync with desktop (https://github.com/BoostIO/boostnote-mobile/issues/63) really breaks that promise. I was hoping that boostnote+syncthing would be the perfect setup, but it doesn't actually work out very smoothly. :(

**Comment by Flexo013** [comment] 2019-11-19 13:17
#1790 is a duplicate of this issue, but since it has funding I'm closing this one.

Let's move our efforts to that thread.

**Closed by Flexo013** 2019-11-19 13:17 UTC
Labels: feature request :zap:, help wanted :sos:
