### ISSUE TITLE
Add text format hotkeys to Markdown Editor

### ISSUE THREAD

**Issue by angelvillalobos303** [BoostIO/Boostnote#3358] opened 2019-11-13 12:57 UTC
### **Current behavior**

Boostnote allows users to modify certain hotkeys related to editor visualization and note management.

### **Expected behavior**

It would be perfect for the markdown editor if you could include additional hotkeys to give simple format to the text, such as bold, italic and underline, maybe using common shortcuts such as CTRL+B, CTRL+K, CTRL+U.

Thanks!

**Comment by Flexo013** [comment] 2019-11-13 16:04
Duplicate of #3142

**Closed by Flexo013** 2019-11-13 16:04 UTC
