### ISSUE TITLE
Opening in full screen Boostnote cannot be closed by pushing close window button.

### ISSUE THREAD

**Issue by sosukesuzuki** [BoostIO/Boostnote#332] opened 2017-03-18 07:08 UTC
I'm using OSX 10.11.2.
When I am using Boostnote in full screen, if I push the window close button or enter command + w, Boostnote will not closed. And, screen is become black. I thought that this cause was Electron, because Slack does the same thing too. However Atom, VSCode, HyperTerm did not such a thing. So, this cause should be not Electron.
![boostnote_notclosebug](https://cloud.githubusercontent.com/assets/14838850/24069830/e458c000-0bf4-11e7-88b6-094c38b98596.gif)

**Comment by VoLuong** [comment] 2017-03-18 17:20
I am using Ubuntu 16.04.2 and Windows 10. So far I couldn't reproduce your bug. This may be platform-specific.

**Comment by kazup01** [comment] 2017-03-22 06:39
Thank you for your reporting @VoLuong san! 
I also have occurred the bug same as Sosuke. *macOS Sierra v10.12.3
This bug may be occurred in mac only, but we'll look it up.

**Comment by akashnimare** [comment] 2017-03-28 20:38
This is not a bug, it's the expected behavior of an app on macOS.

**Comment by VoLuong** [comment] 2017-03-29 00:58
@akashnimare Nah, you got the issue wrong. It's not that the app didn't close that they were complaining about. Look at the GIF and see how the screen turns black after pressing the close button.

**Comment by asmsuechan** [comment] 2017-03-29 01:35
Actually, the behavior is correct for electron. And you, check them  https://github.com/electron/electron/pull/7817, https://github.com/BoostIO/Boostnote/pull/349.

**Comment by sota1235** [comment] 2017-04-22 02:45
It will be fixed on next release.

**Closed** 2017-04-22 09:35 UTC
Labels: Bug, Next Release
