### ISSUE TITLE
On linux, cannot activate the finder

### ISSUE THREAD

**Issue by ahhsia** [BoostIO/Boostnote#1044] opened 2017-10-30 23:18 UTC
Hitting the hotkey for finder does not bring it up on linux. (Running RHEL 7.4)
Instead it makes the menubar visible. 
Changing the hotkey to something else, even very simple like  `Ctrl + X`
doesn't toggle the finder, so it is probably not a function of the hotkey being pre-empted by the desktop hotkeys. 

![screenshot from 2017-10-30 17-14-09](https://user-images.githubusercontent.com/2042495/32200263-5b84dad0-bd96-11e7-98ae-d72a46d87ef2.png)

**Comment by Hedronmx** [comment] 2017-11-01 23:01
Can confirm, happens in Elementary OS

**Comment by whizark** [comment] 2017-11-20 12:01
`lib/main-app.js` seems not to spawn finder window process on Linux.
After I add `spawnFinder()` to [lib/main-app.js](https://github.com/BoostIO/Boostnote/blob/master/lib/main-app.js#L111), it works (at least on Ubuntu).

The feature has been removed by [Disable Finder and Auto-update on Linux · BoostIO/Boostnote@cfa251b](https://github.com/BoostIO/Boostnote/commit/cfa251b1580260e9e01139e706aa854dcc996675) on 7 Apr 2016, but I cannot find the reason.

![finder](https://user-images.githubusercontent.com/1211058/33016997-004b116c-ce34-11e7-90e9-4e351672ccc8.gif)

**Comment by whizark** [comment] 2017-11-20 12:21
The reason is probably [Known bugs · Issue #6 · BoostIO/Boostnote](https://github.com/BoostIO/Boostnote/issues/6#issuecomment-205076437).

On Unity Ubuntu, I confirmed Finder can be closed by CTRL+Q or clicking close button on main window.
Another issue, when I CTRL+Q on Finder window, Finder is closed but I cannot open again.

**Closed** 2018-01-17 04:53 UTC
