### ISSUE TITLE
Images get deleted randomly after dragging them in a note

### ISSUE THREAD

**Issue by mfouet** [BoostIO/Boostnote#3460] opened 2020-02-05 00:17 UTC
# Current behavior

As covered in issues [#3203](https://github.com/BoostIO/Boostnote/issues/3203) and [#3424](https://github.com/BoostIO/Boostnote/issues/3424), images are randomly deleted after dragging an image file in the note. Re-dragging them always leads to the same behavior. I have to change the name of the file I am dragging to have a change of Boostnote not deleting it afterwards...

![image](https://user-images.githubusercontent.com/15130969/73798751-b4942500-4768-11ea-94bc-ca9d2aea01f1.png)

The "fix" provided [#3225](https://github.com/BoostIO/Boostnote/pull/3225) is very detrimental to storage space quickly as from what I understand, if I remove the link to the image in the note, the image will not be deleted?

# Expected behavior

Boostnote should never delete included and currently referenced images! (I am glad I kept copies of them...)

# Steps to reproduce

1.   Drag 10 different images on a note
2.  Quite boostnote or restart computer
3.  Count how many images are left

# Environment

- Version : 0.14.0
- OS Version and name : 10.14.6 Mojave

**Comment by Flexo013** [comment] 2020-02-06 20:53
Duplicate of #3348

**Closed by Flexo013** 2020-02-06 20:53 UTC
