### ISSUE TITLE
Pasting images directly into markdown editor

### ISSUE THREAD

**Issue by oywi** [BoostIO/Boostnote#3381] opened 2019-11-27 21:47 UTC
# Current behavior
When pasting an image from clipboard to the markdown editor, e.g. a screenshot, nothing happens.

# Expected behavior
Pasting an image from the clipboard into the markdown editor should

- Save the image to attachments
- Paste a markdown inline image link

# Steps to reproduce

1. Copy an image to the clipboard
2. Attempt to paste it into markdown editor

# Environment

- Version : 0.13.0
- OS Version and name : Windows 10 x64 10.0.18363

**Comment by Flexo013** [comment] 2019-11-28 13:58
I remember running into this issue every now and then, but currently I am unable to reproduce it on Windows 10. I tried with right-click copying an image and using a printscreen copied image.

@oywi What and how are you exactly copying? Maybe that will help with reproducing it.

**Comment by arcturus140** [comment] 2019-11-28 22:06
use Ctrl + v to paste. ☝️

**Comment by kingvagabond** [comment] 2019-12-03 17:49
Looks like Ctrl + Shift + v is a great and additional feature to normal paste.

Right now:
(1) If I select a single image from browser and paste into BoostNote markdown editor, the image file can be copied to local storage.
(2) If I select mixed content with text and image from browser and paste into BoostNote, only text is pasted. Image file will be missed out.
(3) If I select mixed content with text and image from browser and paste with Ctrl + Shift + v, text is pasted, but image will be pasted via online link - no storage locally.

(3) is useful in some situations. For mobile notes, this may be very good. Or, for situations with limited cell network bandwith, this may be very good option. But it may be even useful if (2) can be fulfilled as (1). That is, when you select mixed text with images from browser and do normal paste into BoostNote, all texts and images will be pasted, with images saved in local storage. This is a feature that I consider a must-have feature for note taking tools.

**Comment by arcturus140** [comment] 2019-12-03 23:10
> Looks like Ctrl + Shift + v is a great and additional feature to normal paste.

don't forget about smart paste in your settings 😜. Personally I don't use it so I'm not sure about it's behaviour. Anyway boostnote supports paste as unformatted text, which is why you are missing the images, and formatted paste as markdown. 

what you need could be implemented similar to excel / calc which allows multiple options for formatted paste.

**Comment by Flexo013** [comment] 2019-12-04 09:31
@oywi  Is your issue the same as what @kingvagabond mentions?

**Comment by arcturus140** [comment] 2019-12-04 15:10
@Flexo013 they are different: first is a bug report (investigation), second a feature request

**Comment by Flexo013** [comment] 2019-12-04 16:22
Sorry if I was unclear. What I meant was:

@oywi Are you pasting text with images or pure images?

---

Also I might close this soon (for now) if we don't get more info from @oywi, since we can't reproduce this bug.

**Comment by oywi** [comment] 2019-12-15 10:26
@Flexo013
I often use the windows screenshot function (WIN + Shift + s), which copies an image to the clipboard. I was not able to paste this directly with (Ctrl + v).

@arcturus140 
I was not aware of the Ctrl + Shift + v functionality. This solved the problem for me.
That's it, thanks!

**Closed** 2019-12-15 23:22 UTC
Labels: needs more info :information_source:
