### ISSUE TITLE
Admonitions and diagrams not rendering in 0.9.0 (Windows 10)

### ISSUE THREAD

**Issue by chayac** [BoostIO/Boostnote#3635] opened 2020-09-07 21:37 UTC
# Current behavior

I am trying to render [this file](https://raw.githubusercontent.com/TobseF/boostnote-markdown-cheatsheet/master/BOOSTNOTE_MARKDOWN_CHEAT_SHEET.md) as a note, and many things are not rendering, including admonitions and charts. I've tried using examples from the Mermaid docs as well and haven't been able to get them to render. I've tried both regular paste and shift-paste, as well as typing in the code directly. I've also tried different themes with the same result.
![admonition](https://user-images.githubusercontent.com/18560340/92417415-d696c100-f116-11ea-831d-57990c17bcc7.png)
![charts](https://user-images.githubusercontent.com/18560340/92417416-d72f5780-f116-11ea-96f8-812ecd00ec57.png)

# Expected behavior

The correct rendering is shown [here](https://github.com/TobseF/boostnote-markdown-cheatsheet).
![admonition-correct](https://user-images.githubusercontent.com/18560340/92417495-5755bd00-f117-11ea-8349-142d2611ba1d.png)
![mermaid-correct](https://user-images.githubusercontent.com/18560340/92417496-591f8080-f117-11ea-9fa1-f09f8b9a9d19.png)

# Steps to reproduce

1. Paste [code](https://raw.githubusercontent.com/TobseF/boostnote-markdown-cheatsheet/master/BOOSTNOTE_MARKDOWN_CHEAT_SHEET.md) into a new note.
2. Look at the rendered output. 

# Environment

- Boostnote version: 0.9.0
- OS version and name: Windows 10

**Comment by Flexo013** [comment] 2020-09-13 10:01
Duplicate of https://github.com/BoostIO/BoostNote.next/issues/474

(and wrong repo)

**Closed by Flexo013** 2020-09-13 10:01 UTC
