### ISSUE TITLE
Ordering bug

### ISSUE THREAD

**Issue by vcvetkovs** [BoostIO/Boostnote#2602] opened 2018-11-11 22:15 UTC
# Current behavior

When changing saved doc ordering from 'Updated' to 'Alphabetically' all works great but when you switch to another folder sorting dropdown value stays the same (Alphabetically) but docs are ordered in 'Updated' order. Workaround is to set value to 'Updated' (after that nothing changes) and then back to desired value.

# Expected behavior

I think it would be better when it orders all docs in alphabetical order after switching folders. 

# Steps to reproduce

1. Change doc ordering to 'Alphabetically'
2. Switch to another folder
3. See that default ordering is applied (Updated)

# Environment

- Version : 0.11.10
- OS Version and name : Windows 10 x64

**Comment by arcturus140** [comment] 2018-11-12 09:43
@vcvetkovs the intended behaviour is to remember each setting on a folder basis. You should be able to set your order for every folder individually and ordering should apply accordingly. The default ordering is 'Updated'.

Unfortunately I was not able to replicate your issue, could you record it?

# Environment

- Version : 0.11.10
- OS Version and name : 16.04 Ubuntu
- OS Version and name : 1803 Windows 10 Pro

**Comment by vcvetkovs** [comment] 2018-11-12 20:48
https://www.dropbox.com/s/1492j1tzjxf131s/bug.avi?dl=0

**Comment by Flexo013** [comment] 2019-08-13 18:32
This issue is fixed in the latest version of Boostnote.

**Closed by Flexo013** 2019-08-13 18:32 UTC
