### ISSUE TITLE
Exported image source path is incorrect

### ISSUE THREAD

**Issue by alelom** [BoostIO/Boostnote#2815] opened 2019-01-17 19:16 UTC
# Current behavior

Images source path incorrectly placed by Boostnote. It inserts the '%5C' instead of the character '/'.
Therefore source path looks like:
`src="attachments%5C9fad04b1.PNG"`
when it should be:
`src="attachments/fad04b1.PNG"`

Result is that the HTML has broken images links:
![untitled](https://user-images.githubusercontent.com/6352844/51342525-16b1b780-1a8c-11e9-8f04-0d84a0dc8bfa.png)

Replacing the wrong characters in the HTML file solves the problem.

# Steps to reproduce

1. Insert any image with Drag&Drop
2. Export in HTML

# Environment

- Version : 0.11.12
- OS Version and name : Windows 7

**Comment by MiloTodt** [comment] 2019-01-18 01:18
Can confirm that this error is present on Windows 10 with the official Boostnote release.

It is not present when on the masterbranch of 0.11.13. I think this issue has been addressed and fixed in the new version.

**Comment by ehhc** [comment] 2019-02-24 14:37
In the current version the issue is present again. I think that's also what is mentioned here: https://github.com/BoostIO/Boostnote/issues/2834#issuecomment-466468377

**Comment by incredibleweirdo** [comment] 2019-05-30 16:48
Hello,
I want to report that I am experiencing this issue as well, though I'm not 100% certain it is the same.
When I export HTML, the image source path has an additional directory specified that does not exist/is not created in the attachments folder. 
When exporting HTML, any images in the markdown are exported directly in the attachments folder that is created:
![image](https://user-images.githubusercontent.com/1223976/58649023-ef7fb800-82bf-11e9-9db5-fe4ec5a64b63.png)
However, the path in the HTML files contains an additional directory above attachments which does not exist:
![image](https://user-images.githubusercontent.com/1223976/58649092-176f1b80-82c0-11e9-91fd-b273b278adb4.png)

**Comment by incredibleweirdo** [comment] 2019-05-30 17:42
More to add!
In dealing with both #2968 and #3018 I found that if I make an edit to "fix" those issues, I can see that the image source path is still bad in 0.11.16 and in 0.11.17. There is still an extra directory in the attachments folder which does not exists, specified in the path.
However, there is also **another issue** with the generated path, in 0.11.16 and 0.11.17 - the image source path in the HTML (and maybe PDF? the PDF images are also broken) no longer references the attachments folder - it references **:storage** at the start of the path:
![image](https://user-images.githubusercontent.com/1223976/58652093-a5023980-82c7-11e9-8c45-136d39cd70fd.png)

**Comment by ehhc** [comment] 2019-05-31 07:25
@incredibleweirdo can you have a look, if this pr fixes your problem? https://github.com/BoostIO/Boostnote/pull/2897

**Comment by incredibleweirdo** [comment] 2019-05-31 15:31
@ehhc I cannot test that PR, sadly. I get an error when running `yarn` on that PR's branch. 
```
$ yarn
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/js-sequence-diagrams/-/js-sequence-diagrams-1000000.0.6.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "D:\\projects
\\Boostnote\\yarn-error.log".
```

**Comment by ehhc** [comment] 2019-05-31 16:15
@incredibleweirdo i'm sorry to hear that... i fear i don't have the time to look into the bug :( 
maybe one of the maintainer @Rokt33r @ZeroX-DG  has time and an idea how to fix it? Maybe they even can have a look at the various PRs? :)

**Comment by incredibleweirdo** [comment] 2019-05-31 16:47
@ehhc I was able to finally test, see my comment here -https://github.com/BoostIO/Boostnote/pull/2897#issuecomment-497767798

**Comment by Flexo013** [comment] 2019-10-30 11:26
Duplicate of #2785

**Closed by Flexo013** 2019-10-30 11:26 UTC
Labels: bug :bug:, level 1 :grey_exclamation:
