### ISSUE TITLE
Right-click copy function and right-click to switch to preview interface conflict

### ISSUE THREAD

**Issue by yuamera** [BoostIO/Boostnote#3144] opened 2019-07-24 10:18 UTC
# Current behavior
right-click on the note to copy and select all
Cannot switch the preview and edit  by right-click

# Expected behavior

I hope to switch the preview and edit by right-click.

# Environment

- Version : 0.12.0
- OS Version and name 🇲🇴 MacOS Mojave Version 10.14.6

**Comment by Flexo013** [comment] 2019-07-24 11:09
Confirmed this bug on Windows 10.
![image](https://user-images.githubusercontent.com/4507015/61789015-e1f43380-ae13-11e9-90ad-37053f4af220.png)
This 'Switch to Preview' setting no longer works due to the introduction of the right-click copy/select all feature. Which was introduced in #3066.

**Comment by wluu** [comment] 2019-07-24 17:51
To workaround this issue, I had to manually click on the Toggle Mode to get back to my edit view:
![bug](https://user-images.githubusercontent.com/1141338/61816306-fb3fb480-ae00-11e9-852d-79201eab8b95.gif)

**Comment by AnthonyWebDev** [comment] 2019-07-24 18:00
Yop, same issue there. On MacOs.

**Comment by fsultani-aspiration** [comment] 2019-07-24 20:22
Same.

**Comment by Flexo013** [comment] 2019-07-25 12:04
As a work-around you can change the setting to double click. As soon as a fix has been released you can switch it back.

**Comment by fsultani-aspiration** [comment] 2019-07-25 17:35
`ctrl + click` on Mac still seems to work.

**Comment by RonWalker22** [comment] 2019-07-30 19:31
What is the plan to resolve this bug? 

If a user has the switch preview setting 'on right click' enabled, they must have Context Menu disabled?

**Comment by gerroon** [comment] 2019-08-23 23:29
@Flexo013 

There is no double click, but there is "when editor blurred Edit on double click" which makes no sense :(

**Closed** 2019-08-24 04:37 UTC
Labels: bug :bug:, level 1 :grey_exclamation:
