### ISSUE TITLE
No longer shows check list progress bar

### ISSUE THREAD

**Issue by tewe** [BoostIO/Boostnote#1589] opened 2018-02-26 10:23 UTC
In v0.10.0 I can no longer see in the note list how many `- [ ]` I checked off. Downgrading to v0.9.0 helps.

**Comment by RomanKlopsch** [comment] 2018-02-26 10:36
Which operating system are you using?
And which way did you install the new version?
I can't reproduce the bug on Ubuntu / 17.10 (installed due the deb package)

**Comment by tewe** [comment] 2018-02-26 12:44
Sorry, macOS 10.13.3, both auto-update and the DMG.

**Comment by pfftdammitchris** [comment] 2018-02-26 14:19
Working on windows for me. Seems like a macOS issue. Hmm

**Comment by Rokt33r** [comment] 2018-02-27 12:08
Hmm... that's weird. It works fine for me too. I'm using macOS 10.13.3 too.

**Comment by tewe** [comment] 2018-02-27 16:16
It does not work fine for you. Here is how 0.9.0 looks, not the progress bar:

<img width="1401" alt="boostnote" src="https://user-images.githubusercontent.com/645412/36740168-ef79deb2-1be1-11e8-8117-f835b3fedab7.png">

**Comment by RomanKlopsch** [comment] 2018-02-27 17:38
Well, seems like we misunderstood you.
I have to correct myself: It does **not** work for me

**Comment by RomanKlopsch** [comment] 2018-02-27 17:52
I managed to get the progress-bar back by changing the display type of
>.NoteItem__item-bottom___browser-components-

from *flex* to *block*.
I don't know, whether this tweak breaks something else but it seems to solve the issue.

**Comment by Rokt33r** [comment] 2018-02-28 07:16
@RomanKlopsch If you don't mind, you can submit a PR with your solution! So, we can review and merge it. How about it? 😄

**Comment by RomanKlopsch** [comment] 2018-02-28 09:02
I am looking forward to fix this in the afternoon

**Comment by Rokt33r** [comment] 2018-02-28 09:20
I'll gladly wait for it! ❤️ ❤️

**Comment by RomanKlopsch** [comment] 2018-02-28 15:16
#1614 here we go...

**Comment by yosmoc** [comment] 2018-05-16 20:53
@Rokt33r please close this issue.

**Closed** 2018-10-10 06:19 UTC
Labels: bug :bug:
