### ISSUE TITLE
feature request: add hotkeys

### ISSUE THREAD

**Issue by Laggkind** [BoostIO/Boostnote#1430] opened 2018-01-17 08:21 UTC
I looked through the feature request, but I haven't found this one, although I am confused whether this option might be already there and I am just missing it. I would like to request the possibility to add custom hotkeys for different actions in the hotkey section of my preferences: in the best case to assign a hotkey to every UI-button. 
As I said, my boostnote-version doesn't appear to have this feature, I am using boostnote v0.8.20 on Ubuntu 17.10. If I missed something, I would be happy to be corrected.

**Comment by sosukesuzuki** [comment] 2018-01-17 10:27
You are not mistaken.:smile: We'll discuss about your feature request:+1:

**Comment by tatoosh** [comment] 2018-03-30 19:44
What abput global hotkeys for example new boostnote ?

**Comment by Flexo013** [comment] 2019-08-07 12:08
Duplicate of #2645

**Closed by Flexo013** 2019-08-07 12:08 UTC
Labels: discussion :speech_balloon:, feature request :zap:
