### ISSUE TITLE
Snippet notes are not exported

### ISSUE THREAD

**Issue by gerroon** [BoostIO/Boostnote#2870] opened 2019-02-07 18:18 UTC
Hi

I am using Boostnote 0.11.13 on Win 10 x64

It seems like snippet notes are not exported at all, please add this feature because the users might not realize that this is not happening :(

Btw I am not a js or electron developer and i do not know what developer tools you are asking for.

Steps to produce the issue

- Choose "Snippet Note" as your default note type
- Make Python as the default language
- Restart to make sure all is set
- Choose a folder from the left pane
- Add couple new snippets/notes 
- right click on that folder
- export txt/md

In both cases the snippet notes are not epxorted :(

**Comment by Flexo013** [comment] 2019-08-20 19:42
Duplicate of #1097

**Closed by Flexo013** 2019-08-20 19:42 UTC
Labels: feature request :zap:
