### ISSUE TITLE
Switich to preview(on right click) does not work on preview mode

### ISSUE THREAD

**Issue by imaojun** [BoostIO/Boostnote#3196] opened 2019-08-02 02:29 UTC
# Current behavior
updated version 0.12.1 Switch to preview(on right click) does not work on preview mode.
In earlier versions, both preview and edit modes could trigger with a right click.
However, in this version of preview mode, right click is to copy and select all features.
So I can't quickly switch to edit mode.
Can only switch to the simultaneous preview and edit mode by clicking the menu button.

# Expected behavior
both preview and edit modes could trigger with a right click.

# Steps to reproduce
1. updated version 0.12.1(Earlier versions I used normally）
2. set Switch to preview(on right click)
3. Use the right click to switch to MD preview mode, then right click again and try to switch back (this doesn't work)

# Environment

- Version :Boostnote 0.12.1 
- OS Version and name :Archlinux

**Comment by avence12** [comment] 2019-08-02 03:27
I encounter the same issue. 
The current workaround is to setup `Switch to Preview` as `When Editor Blurred, Edit on double click`.
However, right-click is much more convenient and hope to get fixed.

**Comment by Flexo013** [comment] 2019-08-02 09:43
Duplicate of: #3144

**Closed by Flexo013** 2019-08-02 09:43 UTC
