### ISSUE TITLE
Cursor not appearing in the correct spot when toggling fullscreen mode.

### ISSUE THREAD

**Issue by K-log** [BoostIO/Boostnote#2447] opened 2018-09-30 22:38 UTC
# Current behavior
When switching to or from Fullscreen mode, the cursor doesn't appear to line up with the lines of text. In order to "reset" the cursor, you have to start typing and/or press enter and the cursor will jump to the correct position. Sometimes portions of the text won't appear either and those will also reappear when you start typing.

# Expected behavior

The cursor should remain in the same position before and after toggling fullscreen mode. One should not be required to start typing to reset the cursor position to the correct spot.

# Steps to reproduce

- Note: I have not been able to reproduce this error with the developer console open.
- Note: This most often happens from turning on fullscreen mode. It happens less often when toggling it off.

1.  Create a new document.
2.  Fill it with a few lines of text.
3.  Make sure the cursor is on the text.
4. Toggle fullscreen on and off.

# Environment

- Version : Boostnote 0.11.9
- OS Version and name : Microsoft Windows 10  Home, 10.0.17134 Build 17134

**Comment by daiyam** [comment] 2018-10-01 14:31
duplicate of #2397, it's fixed in the next release.

**Comment by ZeroX-DG** [comment] 2018-10-02 11:11
Fixed in next release

**Closed by ZeroX-DG** 2018-10-02 11:11 UTC
