### ISSUE TITLE
code syntax highlight not working 

### ISSUE THREAD

**Issue by ericyan3000** [BoostIO/Boostnote#3075] opened 2019-06-12 21:58 UTC
# Current behavior

The code syntax highlight feature is not working on either the editor or the preview window.
![image](https://user-images.githubusercontent.com/8907603/59389154-7bfb9300-8d22-11e9-8e11-d0e469efdb13.png)

# Expected behavior

The code syntax should be highlighted in different colors.

# Steps to reproduce

I just installed the Boostnote on Windows and ran under the default setting.

# Environment

- Version : 0.11.17
- OS Version and name: Windows 10 Pro Version 1809
- The same problem doesn't reproduce on my Linux machine.

**Comment by afridley** [comment] 2019-06-14 02:41
It looks like on Version 0.11.17 on windows every editor theme is broken except default
![defaultTheme](https://user-images.githubusercontent.com/34749972/59479847-024bce00-8e24-11e9-8196-de8cd52bcaa6.PNG)
![duotoneDark](https://user-images.githubusercontent.com/34749972/59479848-024bce00-8e24-11e9-9103-ecb72a4a3f0f.PNG)

**Comment by Flexo013** [comment] 2019-06-14 08:13
Duplicate of #3018

**Closed** 2019-06-14 23:33 UTC
