### ISSUE TITLE
Text exceeds current input window

### ISSUE THREAD

**Issue by guanqun-yang** [BoostIO/Boostnote#3169] opened 2019-07-26 17:33 UTC
# Problem

In the latest version of BoostNote (0.12.0), when contents are entered in the text input window (left), they always exceed the border and this makes it difficult to make updates to contents. In this following example, "independent thinking" does not automatically go to the second line but continue in the first line instead. At the same, since the observation that the scroll bar is not provided in the bottom, I am suspecting this behavior potentially comes from certain buggy update. In fact, when an older version (0.11.15) is installed, this particular behavior disappears. 

![image](https://user-images.githubusercontent.com/36497361/61969903-7be0eb00-af90-11e9-88b0-ecd3fd66ad38.png)

Platform: Windows 10

**Comment by Flexo013** [comment] 2019-07-26 23:27
The scrollbar being gone is indeed a problem caused by the update to 0.12.0. The hotfix for this should come out today or tomorrow. So keep an eye out for that.

Duplicate of: https://github.com/BoostIO/Boostnote/issues/3145

**Closed by Flexo013** 2019-07-26 23:27 UTC
