### ISSUE TITLE
Long code lines do not wrap in PDF exports

### ISSUE THREAD

**Issue by dmast3r** [BoostIO/Boostnote#2531] opened 2018-10-24 15:58 UTC
# When a code snippet is exported to PDF and if a line is too long, it is only visible up to a certain length. While this works fine when exporting to HTML.

**Comment by Flexo013** [comment] 2019-11-30 17:30
Preview:
![image](https://user-images.githubusercontent.com/4507015/69903856-76ad0600-139f-11ea-874c-13f64555ddef.png)

PDF export:
![image](https://user-images.githubusercontent.com/4507015/69903861-83c9f500-139f-11ea-870c-5fded7021ce3.png)

Version 0.13.0

**Comment by Flexo013** [comment] 2019-11-30 18:00
Duplicate of #2776

**Closed by Flexo013** 2019-11-30 18:00 UTC
Labels: bug :bug:, level 1 :grey_exclamation:
