### ISSUE TITLE
Feature: subfolders

### ISSUE THREAD

**Issue by esmeepeters** [BoostIO/Boostnote#467] opened 2017-04-21 19:05 UTC
When you create a new folder, it would been nice you can add the parent folder. So you can create submaps.

**Comment by klauscfhq** [comment] 2017-04-22 00:56
Great suggestion! Though probably this is a duplicate of #125 , so you may want to subscribe there for updates : )

**Comment by esmeepeters** [comment] 2017-04-22 15:19
It's indeed the same request. Thanks for your suggestion, didn't see it before. I'll subscribe to this issue for the updates 👍

**Closed** 2017-04-22 15:19 UTC
Labels: Discussion
