### ISSUE TITLE
Image not created in the 'attachments' folder or 'image' folder

### ISSUE THREAD

**Issue by eugenia1815** [BoostIO/Boostnote#2020] opened 2018-06-01 03:04 UTC
# Current behavior

<img width="678" alt="image" src="https://user-images.githubusercontent.com/33351735/40818714-d71132b8-659b-11e8-8f86-e2b36c27ab19.png">
<img width="841" alt="image" src="https://user-images.githubusercontent.com/33351735/40818776-2e8d7ede-659c-11e8-8d80-69f5b82615d6.png">

# Expected behavior

Image should be created automatically in either 'attachments' folder or the 'image' folder when I paste to Boostnote. But nothing happened. 

# Environment

- Version : v0.11.5
- OS Version and name : macOS Sierra 10.12.6

**Comment by kazuedo** [comment] 2018-06-06 13:34
I am in the same situation.

**Comment by ehhc** [comment] 2018-06-14 14:28
Is it solved with the new version? If yes, could you close this issue? :)

**Comment by kazuedo** [comment] 2018-06-14 23:38
I confirmed the problem was solved. Thank you!!

**Comment by ehhc** [comment] 2018-06-15 06:33
@Rokt33r  or @kazup01 could you close this issue?

**Comment by kazup01** [comment] 2018-06-15 06:58
Thank you @ehhc :) v0.11.6 release blog is here! https://boostlog.io/@kazup01/boostnote-v0116-release-5b222a8d44deba005404673a

**Closed by kazup01** 2018-06-15 06:58 UTC
Labels: bug
