### ISSUE TITLE
The export PDF code block is not fully displayed

### ISSUE THREAD

**Issue by javawxx** [BoostIO/Boostnote#3388] opened 2019-12-05 08:05 UTC
# Current behavior

The code block in the document is too long, when exporting PDF file, the code block part is not fully displayed!

![image](https://user-images.githubusercontent.com/12871776/70215437-71253680-1778-11ea-9a04-bf42358c997c.png)

![image](https://user-images.githubusercontent.com/12871776/70215457-7c786200-1778-11ea-8126-8a70ffdafe86.png)

# Expected behavior

The exported PDF file code block shows incomplete parts that can be dragged or wrapped automatically!

# Steps to reproduce

1. Enter a long line of text in the code block
2. Export PDF
3. 

# Environment

- Version : 0.13.0
- OS Version and name : macOS Catalina 10.15.1

**Comment by Flexo013** [comment] 2019-12-06 12:16
Duplicate of #2531

**Closed by Flexo013** 2019-12-06 12:16 UTC
