### ISSUE TITLE
Entering edit mode should not reset scroll position

### ISSUE THREAD

**Issue by dylankb** [BoostIO/Boostnote#3517] opened 2020-03-08 21:37 UTC
# Current behavior

If I scroll to a certain position on the page distinct from the current cursor position (which is default at the top of the page) and enter edit mode - either by clicking the Edit toggle button or click Cmd + e (the shortcut for entering edit mode on MacOS, this is the option I usually use) -  the preview and edit page will jump back to the previous cursor position. This makes it very difficult to edit large documents as it involves double scrolling and/or doing additional text searches once your scroll position has been lost.

<img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/c4e3f72c256a492bbc42b07e21de4c33-with-play.gif"> </a>

# Expected behavior

When edit mode is entered at a scroll position distinct from the cursor position either 
a) the scroll position for the edit window is maintained, or 
b) the cursor position is updated.

Personally option b) would be fine, but perhaps it could surprise some people. Therefore option a) makes the most sense to me.

# Steps to reproduce

This is an issue for me when I'm dealing with documents that contain more than on screen's length worth of content. For example: 

1) navigate to a longer documents with a TOC to make some edits, 
2) click on a section header from the TOC to get to the section I wish to edit
3) I click Cmd+e and then the page jumps back to the current scroll position (in this case it would be the top of the note). 

This can be seen in the video attachment.

# Environment

- Boostnote version: Version 0.15.1 (0.15.1)
- OS version and name: MacOS High Sierra

**Comment by Flexo013** [comment] 2020-03-09 19:29
Duplicate of #3263

**Closed by Flexo013** 2020-03-09 19:29 UTC
