### ISSUE TITLE
Export markdown as PDF error

### ISSUE THREAD

**Issue by ddubson** [BoostIO/Boostnote#3409] opened 2020-01-01 18:28 UTC
# Current behavior

When attempting to export a PDF of a markdown note (containing local images, KaTeX, and some code fragments), right after the dialog to choose the name for the PDF, hitting save closes the dialog but another dialog pops up containing the message `Callback must be a function`.

![image](https://user-images.githubusercontent.com/437269/71644667-60de7980-2c9a-11ea-9abb-ab273f831107.png)

# Expected behavior

PDF should be exported successfully.

# Steps to reproduce

1. Create a note that has KaTeX, local images, code fragments in it.
2. Click the export to PDF button
3. Observe issue

# Environment

- Version : `0.13.0`
- OS Version and name : MacOS Catalina 10.15.2

**Comment by Flexo013** [comment] 2020-01-01 18:47
Duplicate of #3262

**Closed by Flexo013** 2020-01-01 18:47 UTC
