### ISSUE TITLE
[Feature Request] Create Subfolders

### ISSUE THREAD

**Issue by tatoosh** [BoostIO/Boostnote#1789] opened 2018-04-10 06:27 UTC
It would be nice to create Subfolders for better organisation.

**Comment by bimlas** [comment] 2018-04-11 06:54
What do you think about https://github.com/BoostIO/Boostnote/pull/1775#issuecomment-380344905? It gives the ability to navigate in your notes like you do in a directory tree.

**Comment by Airgunster** [comment] 2018-10-01 19:55
@bimlas, yes, I agree that it gives you to navigate in tags clearly (btw, thanks a lot for this feature), however it's not the same as having sub-folders (as you may have few sub-folders and many, many tags (and then it will be painful to navigate (as there are no filter in tags))).

@Rokt33r, what do you think? I think that many people are interested on this, and it maybe relatively easy to implement?

**Comment by mattkoskela** [comment] 2018-11-09 20:05
This is a duplicate of #586

**Comment by Flexo013** [comment] 2019-07-27 16:16
And also a duplicate of #125

**Closed by Flexo013** 2019-07-27 16:16 UTC
Labels: feature request :zap:
