### ISSUE TITLE
Different between style at preview and style at PDF extract

### ISSUE THREAD

**Issue by tomerror** [BoostIO/Boostnote#3340] opened 2019-11-02 06:51 UTC
# Current behavior
I'm writing a code block after I change his style at UI settings, but when I want to extract to PDF the style didn't change.
This is how it's looking at Boostnote
![image](https://user-images.githubusercontent.com/13800577/68067264-07ff6d00-fd4d-11e9-97b3-b77deed0fd08.png)

This is how it's looking after PDF extract
![image](https://user-images.githubusercontent.com/13800577/68067284-3715de80-fd4d-11e9-9350-2304a895dd44.png)

# Expected behavior
I would like that after I extract to PDF the style remain like it was at the program

# Steps to reproduce
1. Typing a text
2. Click on info
3. Click on .pdf (PDF logo)
4. Choose a file name
5. Open the PDF and see the problem

# Environment
- Version : 0.13.0
- OS Version and name : Windows 10

**Comment by arcturus140** [comment] 2019-11-02 08:26
duplicate of #3125. From what I can see, development has moved away from coloured PDF to a print optimized format.

**Comment by Flexo013** [comment] 2019-11-04 10:19
Duplicate of #3125

**Closed by Flexo013** 2019-11-04 10:19 UTC
