### ISSUE TITLE
Admonition isn't displayed properly when exported as a Pdf

### ISSUE THREAD

**Issue by OnlineVagrant** [BoostIO/Boostnote#2453] opened 2018-10-01 15:35 UTC
![capture](https://user-images.githubusercontent.com/39413259/46298823-69677200-c576-11e8-823f-6a69a3806386.JPG)

**Comment by Flexo013** [comment] 2019-08-18 20:35
Duplicate of #3127

**Closed by Flexo013** 2019-08-18 20:35 UTC
Labels: bug :bug:
