### ISSUE TITLE
Add outline view / TOC

### ISSUE THREAD

**Issue by imageslr** [BoostIO/Boostnote#1716] opened 2018-03-22 04:21 UTC
Such as Typora:

![image](https://user-images.githubusercontent.com/17822028/37751122-802ded04-2dcb-11e8-8ae2-6e21083222f4.png)

**Comment by rayou** [comment] 2018-03-22 04:27
This is a very good idea. For people who writes articles or long documentation would be helpful.

**Comment by Flexo013** [comment] 2019-07-28 17:17
This will probably be fulfilled by this new feature from this issue: #3172

**Comment by Flexo013** [comment] 2019-08-21 09:38
Duplicate of #2294 (funded)

**Closed by Flexo013** 2019-08-21 09:38 UTC
Labels: feature request :zap:
