### ISSUE TITLE
Strikethrough using two tildes does not work on view-mode

### ISSUE THREAD

**Issue by fklement** [BoostIO/Boostnote#3332] opened 2019-10-30 10:55 UTC
# Current behavior
When I add two tildes `~~` in front of the text it gets strikethrough in editing mode but not in view mode.

# Expected behavior
It should get strikethrough in both modes.

# Steps to reproduce

1. Open editor
2. Open new note
3. Copy this into the editor: `~~this is a simple test`

# Environment

- Version : Boostnote 0.13.0
- OS Version and name : Mac OS Mojave

**Comment by Flexo013** [comment] 2019-10-30 13:18
This is caused by the closing `~~` characters being omitted.

``~~this is a simple test~~`` does work properly. The markdown is rendered properly. The preview in the editor is not, but I can imagine this is done intentionally. That way when writing you don't first have to make your opening and closing characters and then go back to write in between. Rather you could just write left-to-right and keep track off closing your styling when you want.

Here is an example demonstration with GitHub markdown:
~~this is a simple test with closing~~
~~this is a simple test without closing

**Closed** 2019-11-01 08:10 UTC
Labels: won’t fix :x:

**Comment by fklement** [comment] 2019-11-03 12:56
@Flexo013 Ahhhh my fault. Thank you for clarification.
