### ISSUE TITLE
Why boostnote don't support to create multi-layer folder? only support to create markdown note or code.

### ISSUE THREAD

**Issue by Crisescode** [BoostIO/Boostnote#3247] opened 2019-09-14 03:22 UTC
# Current behavior

# Expected behavior

# Steps to reproduce

1. 
2. 
3. 

# Environment

- Version :
- OS Version and name :

**Comment by Flexo013** [comment] 2019-09-16 09:59
Duplicate of #125

**Closed by Flexo013** 2019-09-16 09:59 UTC
