### ISSUE TITLE
folder selection

### ISSUE THREAD

**Issue by aakbar5** [BoostIO/Boostnote#2957] opened 2019-04-02 14:26 UTC
# Current behavior
- Select a folder to create a note in a specific folder
- Create a new note
- Selection will be set to All Notes

# Expected behavior
- Selection should stay where user has done before creating note.

**Comment by dredav** [comment] 2019-04-03 04:05
Duplicate of #2823 and #2909

**Closed** 2019-04-07 22:00 UTC
