### ISSUE TITLE
TOC Links broken in HTML export

### ISSUE THREAD

**Issue by Zorlin** [BoostIO/Boostnote#3060] opened 2019-06-06 05:22 UTC
# Current behavior

When exporting a note to HTML with a Table of Contents, the links are broken. The exact same note worked perfectly ~2-3 versions ago (haven't had a chance to bisect yet).

This is how the URL is generated now:

/path/to/file/#Getting-help

# Expected behavior

This is what the URL is supposed to be like:

/path/to/file/Lustre_Testbed_Guide.html#Getting-help

Basically the new Boostnote is stripping off the filename and adding a forward slash...

# Steps to reproduce
* Create a document with at least two headers
* Generate a TOC
* Export as HTML and try to click one

# Environment

- Version : 0.11.17
- OS Version and name : macOS Mojave 10.14.5

**Comment by Zorlin** [comment] 2019-06-06 05:26
Sorry, let me put it another way - it's somehow creating links as "/#blah" instead of "#blah"

**Comment by Zorlin** [comment] 2019-06-06 05:36
Weirdly I don't seem to see the issue in the HTML! Very bizarre...

Issue occurs in both Firefox and Chrome.

**Comment by Flexo013** [comment] 2019-07-27 22:19
This problem is fixed in the 0.12.1 release.

**Comment by sirrah23** [comment] 2019-07-28 00:36
# This is still an issue

Hi @Flexo013 . I can still reproduce this issue with the new v0.12.1 release.

## Steps to reproduce

Here's what I did in order to reproduce this issue independently (note that there's overlap here with what @Zorlin has already done):

1. Download and install Boostnote v0.12.1
2. Open Boostnote and create a new markdown note containing a TOC and eight headers
3. Export the note to HTML
4. Open the HTML file in Firefox v68.0.1 and click on a link in the TOC

## Expected result
The page will to jump to the anchor for the link that I clicked.

## Actual result
Firefox tried to open the link that I clicked as if it were its own HTML file.

## Recordings of the actual and expected results

Here's a recording of this issue in action:

![Boostnote-Issue-3060_Repro](https://user-images.githubusercontent.com/3108640/62000706-e20e6080-b0ab-11e9-9b9e-9099c8bfb455.gif)

and here's a recording of the expected behavior which I got working by manually fiddling with the exported HTML:

![Boostnote-Issue-3060_HTML-Only-Fix](https://user-images.githubusercontent.com/3108640/62000710-ea669b80-b0ab-11e9-8346-45e7965b3e40.gif)

# Root cause analysis

The exported HTML file in my reproduction steps is called `/tmp/repro/3060.html`. However, the base that is set in the exported HTML file header does not reference `3060.html`:

```html
<html>
    <head>
    <base href="file:///tmp/repro/">
```

By changing the base to reference the full filepath, the issue resolves itself:

```html
<html>
    <head>
    <base href="file:///tmp/repro/3060.html">
```

# Follow-up

I've found a few places in the Boostnote export code that I think need to be changed in order to fix this issue for good and I will have a pull request ready soon. In the meantime, if you re-open this issue then I can reference it in any new pull requests.

**Comment by Flexo013** [comment] 2019-07-28 16:48
My apologies for closing the issue prematurely. It is now reopened.

Awesome that you can a PR with a fix ready soon 😄

**Comment by Flexo013** [comment] 2019-08-24 10:40
The fix is merged so it will be part of the release.

**Closed by Flexo013** 2019-08-24 10:40 UTC
Labels: needs investigation :microscope:
