### ISSUE TITLE
Export md file failed：Callback must be a function

### ISSUE THREAD

**Issue by xiangfan211** [BoostIO/Boostnote#3378] opened 2019-11-25 08:13 UTC
windows10：
![QQ截图20191125160947](https://user-images.githubusercontent.com/13128860/69523281-788d5880-0f9e-11ea-9e8f-2fec587b50e3.png)

**Comment by Flexo013** [comment] 2019-11-25 08:20
Duplicate of #3262

**Closed by Flexo013** 2019-11-25 08:20 UTC
