### ISSUE TITLE
Left sidebar broke after updating to 0.15.0

### ISSUE THREAD

**Issue by sradevski** [BoostIO/Boostnote#3502] opened 2020-02-28 09:42 UTC
# Current behavior

I have a bunch of folders to categorize my notes, and after updating to 0.15.0 the scroll broke and some of them are not accessible anymore.

If you set the `height` to some fixed value  in `StorageList__storageList___browser-components-`, then the scroll works as expected. I'd guess the height of the sidebar overflows, but I didn't look in the code in that much detail.

# Expected behavior

I can scroll through the list of folders seamlessly.

# Steps to reproduce

I have 23 folders in a Dropbox integration, just add as many (or maybe more) and try to scroll.

# Environment
- Boostnote version: 0.15.0
- OS version and name: macOS Catalina 10.15.3

**Comment by victorbrca** [comment] 2020-02-28 15:31
I have the same issue on Windows 10 with Boostnote 0.15.0. I can no longer access all my notes.

**Comment by Flexo013** [comment] 2020-02-28 19:33
Duplicate of #3486 

Fix will be released Sunday.

**Closed by Flexo013** 2020-02-28 19:33 UTC
