### ISSUE TITLE
Any kind of Export Not Working

### ISSUE THREAD

**Issue by goldcoders** [BoostIO/Boostnote#3444] opened 2020-01-22 08:28 UTC
When I Try to Export a Markdown to all type format txt , md, pdf, html 
My file manager pop up , in my case im using nemo file manager 
it will pop up then if you set a name for example test.pdf ... 
The File Type is Set to Documents , i dont know but i cannot change the file type...

When i Click Save nothing is Saved

Im Using Archlinux 5.4.12
Window Manager : i3-gaps
File Manager: Nemo
Boostnote version in AUR : 0.14.0-1

**Comment by Flexo013** [comment] 2020-01-22 18:33
Duplicate of #3372

**Closed by Flexo013** 2020-01-22 18:33 UTC
