### ISSUE TITLE
Better filenames for notes

### ISSUE THREAD

**Issue by cossio** [BoostIO/Boostnote#1849] opened 2018-04-20 20:11 UTC
Would it be possible to have better file names for notes? Curently it seems notes have a name based on some hashing. I suggest they include the hashing, plus a word or two from the title.

I keep track of the notes in a git repo. When I see what files changes on a commit, it is meaningless at hte moment because the notes have unintelligible names.

**Comment by Rokt33r** [comment] 2018-04-21 05:01
I agree with you. The current file name is definitely useless. 🤔

**Comment by Flexo013** [comment] 2019-07-28 18:54
Duplicate of #1447

**Closed by Flexo013** 2019-07-28 18:54 UTC
Labels: feature request :zap:
