### ISSUE TITLE
Search result highlight not removed once search bar cleared

### ISSUE THREAD

**Issue by d3vnick** [BoostIO/Boostnote#3131] opened 2019-07-19 10:58 UTC
# Current behavior
When you clear the search bar, the highlighted results are not cleared.

# Expected behavior
If I click on the `x` in the search bar, the highlighted results should be cleared

# Steps to reproduce

0. Put the toggle view to plain text 
1. Search something
2. click `x`
3. results still highlighted 

# Environment

- Version : Boostnote 0.11.17
- OS Version and name : Win 10

**Comment by Flexo013** [comment] 2019-07-19 11:28
Duplicate of: https://github.com/BoostIO/Boostnote/issues/3111

**Closed by Flexo013** 2019-07-19 11:28 UTC
