### ISSUE TITLE
[minor] show application version within app 'Help' menu

### ISSUE THREAD

**Issue by huzibizi** [BoostIO/Boostnote#3615] opened 2020-07-22 13:04 UTC
# Current behavior

There is no option in the Help section of the menu (similar to About Us) to display the version information of the app when it's running. This makes it slightly more difficult to report the version number here on github. 

Right now this information can be found within the 'Preferences' section, which can only be accessed by clicking on the preferences button then going to about.

As a quick fix, you could link 'About' from the Help menu, and use it as a quick way to access Preferences > About, to view the version info. 

# Expected behavior

There should be some option in the Help section that shows the version number, whether its embedded directly in the Help menu, or in a popup that appears when you click 'About Us', it should be there.

The easiest way I guess would be to embed the version number into the help menu, or add an option 'Version' or 'About Us' where if you click it, it'll display the version and other info in a popup, where you can also link back to the main site on. 

# Steps to reproduce

N/A

# Environment

- Boostnote version: Latest windows version  as of 22nd July 2020
- OS version and name: Windows 10 Pro x64

**Comment by huzibizi** [comment] 2020-07-22 14:49
just realised the version info is located in the 'preferences' section. it would be nice if it was easier to find though. same with the preferences section, but maybe its just me lol.

**Comment by Flexo013** [comment] 2020-08-02 12:05
Duplicate of https://github.com/BoostIO/BoostNote.next/issues/350

**Closed by Flexo013** 2020-08-02 12:05 UTC
