### ISSUE TITLE
Duplicated notes using cloud

### ISSUE THREAD

**Issue by AsixJin** [BoostIO/Boostnote#3045] opened 2019-05-28 19:09 UTC
# Current behavior

I have Boostnotes on two machines and I have google drive handling cloud saving for my notes. Whenever I jump from one machine to another and upload my changes from the cloud and open Boostnotes it has a duplicate note for every change I made to any note.

# Expected behavior

# Steps to reproduce

1. Set cloud saving on two different machines using Boostnotes
2. Make changes to note on one machine and upload changes to the cloud.
3. Get on the second machine and pull changes down.
4. The second machine will have duplicate notes for every change made to any note

# Environment

- Version : Both machines are on the latest version
- OS Version and name : Mac Mojave/Linux Mint

**Comment by Flexo013** [comment] 2019-05-31 10:03
Can you check whether both copies of the files are on Google Drive? Do you manually push/pull the changes that have been made to the `.cson` note files?

I suspect this might be a conflict with Google Drive's feature of keeping multiple versions of files.

Could you check if using other cloud services like MEGA or Dropbox causes the same issue of duplicate notes?

**Comment by Flexo013** [comment] 2019-07-18 11:59
For now we are closing this issue, since we can't reproduce this.

@AsixJin Feel free to reopen this issue if you have more information for us.

**Closed by Flexo013** 2019-07-18 11:59 UTC
Labels: Need more information :question:
