### ISSUE TITLE
Add latex support to pdf export

### ISSUE THREAD

**Issue by yvquanli** [BoostIO/Boostnote#3391] opened 2019-12-08 14:28 UTC
Could you please add latex support to pdf export, it's very important to me.
It was a raw latex code after the pdf export.

Version: Boostnote 0.13.0 
OS: windows10 1909

**Comment by yvquanli** [comment] 2019-12-08 14:45
Yeah, I had read about the formula and some words about katex. So, I just want to know what I have to do.

**Comment by Flexo013** [comment] 2019-12-08 18:23
Duplicate of #3342

**Closed by Flexo013** 2019-12-08 18:23 UTC
