### ISSUE TITLE
Automatic line numbering interacts poorly with IP Addresses

### ISSUE THREAD

**Issue by CommanderTso** [BoostIO/Boostnote#3609] opened 2020-07-10 18:47 UTC
Thanks for the product! I love it and use it daily.

# Current behavior

When cutting, pasting, and otherwise working with IP addresses, the app will prepend incremental numbers to IPs pasted or moved to a new line.

This happens with both inserting a carriage return into a one-line list of IPs and with pasting IPs onto a line directly following one that starts with an IP.

I only tested a couple different language formats, but this happened across them all.

# Expected behavior

To be able to paste IPs without altering their text

# Steps to reproduce

Pasting IPs
- Copy this into a new document.  I used Plain Text formatting.
```
10.1.1.1
128.128.128.128
```
- Hit enter
- Result: New line starts with `129.`

Inserting carriage returns
- Paste the following into a new document: `10.1.1.1 128.128.128.128`.  I used Plain Text formatting.
- Move the cursor directly before the first `128.` and hit return
- Result: note now reads as:
```
10.1.1.1
11.128.128.128.128
```

# Environment

- Boostnote version: 0.15.3
- OS version and name: OSX Mojave 10.14.6

**Comment by arcturus140** [comment] 2020-07-10 20:16
this is expected behaviour. As a workaround, wrap your IP addresses as code. You can also opt out of the enumeration by pressing enter in the new line that has automatically been created for you.

**Comment by Flexo013** [comment] 2020-07-11 12:55
Thanks for the report! This will be fixed by #3610.

**Closed by Flexo013** 2020-07-11 12:55 UTC

**Comment by arcturus140** [comment] 2020-07-11 15:04
> Thanks for the report! This will be fixed by #3610.

@Flexo013 #3609 is about supporting IP addresses, #3610 is a different issue. A fix for #3609 is not a fix for #3610. The current behaviour for #3609 works as intended and the expected behaviour for #3609 should be a won't fix.
