### ISSUE TITLE
GitHub Integration and sync

### ISSUE THREAD

**Issue by ram-nad** [BoostIO/Boostnote#3266] opened 2019-10-06 04:39 UTC
## :sparkles: Feature Request
Can we provide `GitHub` integration, in case we want our notes to be saved on `GitHub`?

Possible Options:
 - Link a particular storage with a `repository`
 - Auto commit when user wants to sync

Possible Use Cases:
 - If a team is working on a project then having all the notes related to project saved would be good idea
 - Also if someone wants to publish his notes on `GitHub`
 - Can share `Markdown` files for static sites

**Comment by ram-nad** [comment] 2019-10-06 05:02
I would also like to help in making this feature(if it is accepted) but I am new to this project an have no prior experience working with `electron`. Any suggestions from where to start would be really helpful.

**Comment by Flexo013** [comment] 2019-10-07 06:44
Duplicate of #2792

**Closed by Flexo013** 2019-10-07 06:44 UTC
Labels: feature request :zap:
