### ISSUE TITLE
Paste Image from Screenshot no longer works.

### ISSUE THREAD

**Issue by ivyivylynn** [BoostIO/Boostnote#1953] opened 2018-05-22 06:06 UTC
# Current behavior

Pasting a screenshot from clipboard will create the attachments\sth_dir\sth.png files but the picture won't show up. When open the sth_dir directory in attachments there is actually not file called sth.png there.

# Expected behavior

The pasted screenshot picture should show up and there should be a image file matching sth.png inside of sth_dir directory.

# Steps to reproduce

1. Take a screenshot of anything
2. Paste in a markdown note
3. There will be a placeholder for the pasted image but no image file is created or showed up.

# Environment

- Version : 0.11.5(2018/5/20)
- OS Version and name : Window 10

**Comment by ehhc** [comment] 2018-05-22 07:10
Unfortunately the problem was, that the attachments were referenced by a absolute path and not a relative one. After exiting the edit mode the program thought the attachment was not used and deleted it therefore.. i have fixed it now (at least i hope that.. :) )

**Comment by gaborgulyas** [comment] 2018-05-22 09:38
I have the same issue. Went back to 11.4 where it still works...

**Comment by ivyivylynn** [comment] 2018-05-24 06:29
It's interesting that when I use drag and drop to add the images the program does not delete the attachments when exiting edit mode. It only behaves this way when I paste from clipboard.

**Comment by ehhc** [comment] 2018-05-24 06:36
@ivyivylynn no that’s quite logical. The program deletes all files not referenced in your note. It only uses images referenced by relative links (`:storage/noteKey/fileName`) for this check. Since the pasted images is referenced with an absolute file link (it's a bug fixed by the commit above) that image seems not to be referenced it will be deleted therefore. Drag& drop images are referenced by relative path (as intended) and will not be deleted therefore.

As i said. I committed an PR fixing this problem.. The ball is up to the owner of boostnote to merge my PR now :)

**Closed** 2018-06-04 03:02 UTC
